### PR TITLE
README.md: we also need set $KUBECONFIG env

### PR DESCRIPTION
**Pull request by anjiawei1991**
we need set  $KUBECONFIG enviroment after created the cluster.

### CODE REVIEW

**Comment by anjiawei1991** [comment]
I signed it

**Comment by anjiawei1991** [comment]
I signed it

**Comment by BenTheElder** [comment]
Hi, thanks for the PR.

These instructions are output in the relevant format for the host OS on each platform when you run the `kind create cluster` command. I don't think we should duplicate them here (especially as we need multiple versions depending on your OS / shell) 😅

Technically to use the cluster you may also need to install a client like kubectl but this part depends on your use case for any cluster and isn't included here. 

The actual user guide also covers this in better detail https://kind.sigs.k8s.io/docs/user/quick-start/#interacting-with-your-cluster

**Comment by tao12345666333** [comment]
Thanks for your work.  :+1: 
ButI agree with @BenTheElder 
In this content of README.md, we only need to include the most basic `kind` command itself.

**Pull request closed without merging**
