### PR TITLE
site/.../user/*: Update kubeadm API version

### PR DESCRIPTION
**Pull request by LiliC**
Update kubeadm APIVersion to kubeadm.k8s.io/v1beta2 in examples.

Closes https://github.com/kubernetes-sigs/kind/issues/666

### CODE REVIEW

**Comment by tao12345666333** [comment]
Thanks.

/ok-to-test

**Comment by aojea** [comment]
I think that this only applies to master and k8s versions > 1.15, should we add a note mentioning it? The relationship between kubeadm API version and k8s versions is described in https://github.com/kubernetes-sigs/kind/blob/48f2b327bf69df8a0991ac2ccd13f6d1a949e216/pkg/cluster/internal/kubeadm/config.go#L452

**Comment by LiliC** [comment]
> I think that this only applies to master and k8s versions > 1.15, should we add a note mentioning it? 

By default the 1.15 cluster is created, so not sure it's needed. But if yes where do we want to document that?

**Comment by aojea** [comment]
No worries, just realized about this ... But maybe is not very common, anyway this lgtm, that can be done later if needed

**Comment by BenTheElder** [comment]
the example should absolutely work with the latest default kind.

it is worth knowing that the patches do need to match currently.

looking at options to change how this works as this is something of a UX thorn.

I would not actually use this config either, it merely shows what fields are possible, generally setting all of them should not be required, we might want to clarify that somehow :sweat_smile:

**Pull request merged**
