### PR TITLE
update to go 1.12.9

### PR DESCRIPTION
**Pull request by BenTheElder**

### CODE REVIEW

**Comment by BenTheElder** [comment]
going ahead and filing this, but the image is not available yet. it was already PRed upstream but will take some time to be ready.

**Comment by neolit123** [comment]
:+1: 
/lgtm
/hold

**Comment by BenTheElder** [comment]
it's up now
/retest
/hold cancel

**Comment by BenTheElder** [comment]
pod pending timeout :roll_eyes: (prow)
/restest

**Pull request merged**
