### PR TITLE
Add GA_ONLY option to e2e-k8s script

### PR DESCRIPTION
**Pull request by liggitt**
Supports running conformance tests with only GA APIs/features. See https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/20191023-conformance-without-beta.md for details, and https://github.com/kubernetes/test-infra/pull/16560 for sample use.

Supported values:
* `GA_ONLY=false` (default) - run with default APIs and features
* `GA_ONLY=true` - limit to GA features/APIs as much as possible. special-cases 1.18 and 1.19 (for now) to enable certificates.k8s.io/v1beta1 API and the RotateKubeletClientCertificate feature since those are required for cluster-bringup

My goal was to avoid exposing too much control over the particulars of the kind config/invocation, to allow future flexibility with other desired configurations.

Running this on Kubernetes master with GA_ONLY=true produced a clean conformance run:
```
cd $HOME/go/src/k8s.io/kubernetes
GA_ONLY=true BUILD_TYPE=make ./../../sigs.k8s.io/kind/hack/ci/e2e.sh
...
Ran 277 of 4988 Specs in 4003.726 seconds
SUCCESS! -- 277 Passed | 0 Failed | 0 Pending | 4711 Skipped
```

Verified the API versions enabled on the test cluster while the test was running:
```
kubectl api-versions --kubeconfig=$HOME/.kube/kind-test-config

admissionregistration.k8s.io/v1
apiextensions.k8s.io/v1
apiregistration.k8s.io/v1
apps/v1
authentication.k8s.io/v1
authorization.k8s.io/v1
autoscaling/v1
batch/v1
certificates.k8s.io/v1beta1
coordination.k8s.io/v1
networking.k8s.io/v1
rbac.authorization.k8s.io/v1
scheduling.k8s.io/v1
storage.k8s.io/v1
v1
```

And verified the started components were actually using the limited feature gates:
```
ps -ef | egrep -o -- 'kube.*--feature-gates=[^ ]*?'
kube-scheduler ... --feature-gates=AllAlpha=false,AllBeta=false,RotateKubeletClientCertificate=true
kube-apiserver ... --feature-gates=AllAlpha=false,AllBeta=false,RotateKubeletClientCertificate=true
kube-controller-manager ... --feature-gates=AllAlpha=false,AllBeta=false,RotateKubeletClientCertificate=true
```

```
grep -A 3 feature /var/lib/kubelet/config.yaml 
featureGates:
  AllAlpha: false
  AllBeta: false
  RotateKubeletClientCertificate: true
```

```
grep -A 3 feature /var/lib/kubelet/pods/4950d0c1-5139-4bec-a29f-72e657f5551b/volumes/kubernetes.io~configmap/kube-proxy/config.conf 
featureGates:
  AllAlpha: false
  AllBeta: false
  RotateKubeletClientCertificate: true
```

/cc @BenTheElder

### CODE REVIEW

**Comment by aojea** [comment]
Possible conflicting with https://github.com/kubernetes-sigs/kind/pull/1269

**Comment by liggitt** [comment]
Oh, neat, didn't know that was in progress. Happy to adjust or close in favor of that if it will land shortly.

**Comment by BenTheElder** [comment]
spoke out of band, streamlined a bit.
i'll rebase #1269 on this plus some other changes later today or monday

/lgtm
/approve

**Pull request merged**
