### PR TITLE
remove myself from OWNERS

### PR DESCRIPTION
**Pull request by neolit123**
sorry folks, but with increased involvement downstream after the recent acquisition i need to remove myself from some OWNER files to reduce upstream involvement.

### CODE REVIEW

**Comment by neolit123** [comment]
/assign @BenTheElder @aojea 

best to try to scale the reviewer list more somehow.

**Comment by stmcginnis** [comment]
/lgtm

Sad to see, but definitely understand.

**Comment by aojea** [comment]
/approve

👍 😢

**Comment by BenTheElder** [comment]
Sad to see, thank you so much for all of your contributions over the years.

**Pull request merged**
