### PR TITLE
Remove `exclude-from-external-load-balancers` from single node clusters

### PR DESCRIPTION
**Pull request by howardjohn**
Part of https://github.com/kubernetes-sigs/kind/issues/3506

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
we should probably mention this in the kubeadm "create a cluster" page too.

**Review by BenTheElder — COMMENTED** [review]
just confirming: this was added in 1.21? so this is a no-op for _really_ old unsupported clusters and not worth worrying about version checks.

thanks! LGTM

**Comment by BenTheElder** [comment]
> we should probably mention this in the kubeadm "create a cluster" page too.

Agreed, do you prefer to track that sort of thing at k/website?

**Comment by neolit123** [comment]
> > we should probably mention this in the kubeadm "create a cluster" page too.
> 
> Agreed, do you prefer to track that sort of thing at k/website?

i can log a new k/website ticket.

**Comment by BenTheElder** [comment]
[also confirming for next time, thanks!]

**Pull request merged**
