### PR TITLE
Entrypoint fixup

### LINKED ISSUE #1969: Kubelet: invalid configuration: cgroup-root ["kubelet"] doesn't exist
**What happened**:

Running a node-image built with kind `92f54895`, in github actions, using kind 0.9.0 makes kubelet fail to start with the following error:

>  Dec 07 19:16:44 ovn-control-plane kubelet[994]: F1207 19:16:44.170173     994 server.go:269] failed to run Kubelet: invalid configuration: cgroup-root ["kubelet"] doesn't exist
Dec 07 19:16:44 ovn-control-plane kubelet[994]: goroutine 1 [running]:

**How to reproduce it (as minimally and precisely as possible)**:

I've tried to reproduced it locally without success:
```
./kind.v0.9.0 create cluster --image aojea/kindnode:kind92f54895_k8se1c617a88ec
```

The failing job with the errors and logs is here
https://github.com/aojea/ovn-kubernetes/runs/1512853588?check_suite_focus=true

Bear in mind that github actions have its own docker and we had issues with KIND running there before
```
Client:
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., 0.4.2+azure)

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 22
 Server Version: 19.03.13+azure
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1031-azure
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 6.791GiB
 Name: fv-az183-477
 ID: ZDHP:ZO2E:H6PK:BNIM:UC36:GA3L:TTM6:4HUU:GWDU:GGRT:AMDI:I2E7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: githubactions
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### PR DESCRIPTION
**Pull request by BenTheElder**
cc @aojea 
I think fixes #1969

### CODE REVIEW

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/1980#issuecomment-745823908

**Comment by aojea** [comment]
fixed by https://github.com/kubernetes-sigs/kind/pull/1995

**Comment by BenTheElder** [comment]
in https://github.com/kubernetes-sigs/kind/pull/1995

**Pull request closed without merging**
