### PR TITLE
offline docs

### LINKED ISSUE #345: document offline clusters
xref: https://github.com/kubernetes-sigs/kind/pull/331#issuecomment-466668764

We should also think about how to start breaking up some of these things into seperate advanced guides to keep the quick start focused. unsure on this one, but https://github.com/kubernetes-sigs/kind/issues/303 will be a good one to split out

/kind documentation
/priority important-soon

### PR DESCRIPTION
**Pull request by tao12345666333**
fix #345

### CODE REVIEW

**Comment by BenTheElder** [comment]
rendered: https://deploy-preview-1064--k8s-kind.netlify.com/

**Comment by tao12345666333** [comment]
What I am going to write includes two parts.

1. Use an existing image (this process can also be considered offline when the image exists)

But the Pull image also needs the network, so I am not sure if I need to write it here. According to https://github.com/kubernetes-sigs/kind/pull/331#issuecomment-466674273 it seems meaningful to write it. @BenTheElder  WDYT?

2. Build your own node image

**Comment by BenTheElder** [comment]
> But the Pull image also needs the network, so I am not sure if I need to write it here. According to #331 (comment) it seems meaningful to write it. @BenTheElder WDYT?

the node image must be obtained somehow, the easiest way is to pull it when you have network access.

it could also be transported to a machine by transfering a `docker save` style tarball

**Comment by tao12345666333** [comment]
I didn't describe how to build own node image.
Because I found that the process of building an image is not very suitable for offline use.

@BenTheElder  PTAL. Thanks.

**Comment by tao12345666333** [comment]
https://deploy-preview-1064--k8s-kind.netlify.com/docs/user/working-offline/

**Comment by tao12345666333** [comment]
ping @BenTheElder If you have time, PTAL. Thanks.

**Comment by BenTheElder** [comment]
Image building should be fixed for offline as well but we can document it when that is true.

**Comment by tao12345666333** [comment]
> we should probably mention side loading and if doing HA clusters the loadbalancer image?

ok, I will add it.



> Image building should be fixed for offline as well but we can document it when that is true.

If we build `node-image` with `docker` type (default), we need many other things like `k8s.gcr.io/kube-cross` image and some others for buil kubernetes.

It might be more convenient to use `bazel`, let me try! (I always using `docker` type)

**Comment by BenTheElder** [comment]
> It might be more convenient to use bazel, let me try! (I always using docker type)

bazel is maybe going away upstream

I would just document that you should build *once* online to let the upstream build tools fetch dependencies. this also applies to bazel, which I assure you downloads far more things than the make build.

**Comment by BenTheElder** [comment]
sorry for the ridiculous delay here. everything is crazy right now :-)

**Comment by tao12345666333** [comment]
Be careful :cat: 

Let me update this PR.

**Comment by tao12345666333** [comment]
> bazel is maybe going away upstream

I see related issues https://github.com/kubernetes/kubernetes/issues/88553

**Comment by tao12345666333** [comment]
Add some contents about building node-image and create HA cluster. 

@BenTheElder  PTAL, thanks!

**Comment by tao12345666333** [comment]
ping @BenTheElder  PTAL.  
Thanks. :smile_cat:

**Comment by BenTheElder** [comment]
pong ... 8 days later.
my latency has gone up 😂 :this-is-fine:

**Comment by BenTheElder** [comment]
/lgtm
/approve
we can iterate, this is a wonderful addition, thank you

**Pull request merged**
