### PR TITLE
migrate containerd registry endpoint to hosts.toml

### PR DESCRIPTION
**Pull request by matthyx**
see https://github.com/kubernetes/kubernetes/issues/110312

### CODE REVIEW

**Comment by BenTheElder** [comment]
Were it so easy https://kind.sigs.k8s.io/docs/user/local-registry/

https://github.com/kubernetes-sigs/kind/issues/2875

**Comment by aojea** [comment]
🍿 https://github.com/kubernetes/kubernetes/issues/110312#issuecomment-1265470633

it seems this will take some time

**Comment by BenTheElder** [comment]
I think we will probably have to design a KIND registry config format to shim this, so we can backend it with either containerd inline or the hosts dir.

When doing so we also need to consider the longstanding feature request for a built-in registry user experience.

**Comment by matthyx** [comment]
do you have a KinDEP process ;-) ?

**Comment by aojea** [comment]
> do you have a KinDEP process ;-) ?

there was some try IIRC, I think that Ben also opened an issue about that

**Comment by BenTheElder** [comment]
https://kind.sigs.k8s.io/docs/contributing/getting-started/ points to discussing designs in an issue before moving to implementation. You can see some examples of issues outlining designs.

**Comment by BenTheElder** [comment]
we just removed this config from the base image, we still need a good plan for how users can reasonably switch over with their custom registry configs. we have other much more pressing issues at the moment though.

**Comment by BenTheElder** [comment]
#3122

**Comment by matthyx** [comment]
Yeah, I let that rot a bit... thanks Ben.

**Comment by BenTheElder** [comment]
thanks for the PR, this is going to be a mess to finish sorting out 😅

**Pull request closed without merging**
