### PR TITLE
[WIP] add tentative project logo

### PR DESCRIPTION
**Pull request by BenTheElder**
Just something I hacked up in inkscape based on a previous discussion about kind being like a "ship in a bottle" where the ship is a (kubernetes) container ship :-)

It's not the prettiest thing ever, but I'm starting to figure out hosted docs w/ navigation etc. similar to k/website and I'd like an image for the sidebar-nav and landing page.

We're using a PNG in the docs but I also included the SVG source. The text is a hand edited path export from Roboto, somewhat similar to Kubernetes. The wheel is from the Kubernetes logo, which as far as I can tell is permissible given the scope of this project. Per [usage_guidelines.md](https://github.com/kubernetes/kubernetes/blob/master/logo/usage_guidelines.md#kubernetes-branding-guidelines)

> Acceptable related uses include display, modification, or use of the Kubernetes logo in connection with your compliant implementation, your integration with a compliant implementation, your support for a compliant implementation, your Kubernetes-compatible product, or in collateral, presentations, and marketing materials relating to compliant implementations of Kubernetes.

### CODE REVIEW

**Comment by BenTheElder** [comment]
cc @munnerz, [rendered here](https://github.com/BenTheElder/kind/blob/7d1443aea85a3db25e11a9712afd398ed9ec4cfc/README.md)

**Comment by neolit123** [comment]
@BenTheElder how about making a little logo contest?
like "hey, we are looking for a logo designer for kind and here is what we want our logo to look like"
and accept submissions for N days?

you'd be amazed with the art people can come up with.

**Comment by neolit123** [comment]
attempt.

neolit123-kind-logo-
neolit123-kind-logo-tshirt-design

**Comment by BenTheElder** [comment]
N should be small for the other reason I forgot:
- I intend to submit conformance results soon (like, ideally early this week!) for certification, and we need something to show on the CNCF site!

(Also I love that! Do you have a vector format of that?)

**Comment by neolit123** [comment]
> I intend to submit conformance results soon (like, ideally early this week!) for certification, and we need something to show on the CNCF site!

hm, in that case there might not be enough time?

if you still want to give it a few days let me know how much and we can announce the contest on kubernetes-dev, some slack channels and twitter (i don't have an account), reddit (got an account).

the requirements could be:

- theme - ship in a bottle carrying containers, with k8s logo + text "kind" stamped on the ship
- SVG, high+res transparent PNG
- released under permissive license (e.g. https://github.com/kubernetes/kubernetes/blob/master/logo/LICENSE) and at the same time granting permission to use in the project.

> Do you have a vector format of that?

yes.
https://svgshare.com/i/Agg.svg

**Comment by BenTheElder** [comment]
Thanks! We discussed offline and I think this one (neolit123's) is awesome
enough to go forward with it as an initial logo while we consider how to
handle a contest.

**Comment by BenTheElder** [comment]
closing in favor of @neolit123's :-) 🎉

**Pull request closed without merging**
