### PR TITLE
Fixed wsl command for wsl2 set as default

### PR DESCRIPTION
**Pull request by alfsuse**
Found a small typo in the command "wsl --set-default-version 2" it was missing the dash between default and version.

### CODE REVIEW

**Comment by BenTheElder** [comment]
/hold
unfortunately the Kubernetes projects require the CNCF CLA which seems not to be signed for your account, more details in https://github.com/kubernetes-sigs/kind/pull/675#issuecomment-507207942

**Comment by alfsuse** [comment]
I signed it

**Comment by BenTheElder** [comment]
Thank you!

**Pull request merged**
