### PR TITLE
add ContainerLabels for node (#3068)

### PR DESCRIPTION
**Pull request by icefed**
example usage:
```
- role: worker
  containerLabels:
    dev.orbstack.domains: "*.kind.local"
```

hope this is helpful for https://github.com/kubernetes-sigs/kind/issues/3068.

### CODE REVIEW

**Comment by stmcginnis** [comment]
> the issue is not closed, and i can see it's useful for some users.

That is just ignoring the negative feedback from the maintainers on the issue though. The concerns raised are still valid. The issue should probably be closed at this point, but I think it was left open to allow for more discussion if anyone had ideas that would address those concerns. I don't believe anything has changed to make it worth adding this.

There are other easy ways outside of kind to handle something like this. With the small number of users where this would be needed, it is better to use those approaches than to add more code to kind to cover it.

**Comment by BenTheElder** [comment]
Pleas see https://kind.sigs.k8s.io/docs/contributing/getting-started/#4-reaching-out

We have not agreed to this feature. In general we try to keep the surface of integration to container runtimes minimal and only add essential features, not just useful features.

**Comment by icefed** [comment]
thanks for your reply.

**Comment by stmcginnis** [comment]
Going to close since this isn't a direction we want to take.

/close

**Pull request closed without merging**
