### PR TITLE
docs updates

### PR DESCRIPTION
**Pull request by BenTheElder**
1. Simplify install guide now that go 1.16+ is required. Also fixes https://github.com/kubernetes-sigs/kind/issues/2866
2. Use K8s colors for banner/footer, drop 14+ month banner.
3. gitignore hugo lock file from newer hugo versions
4. Simplify development: Use a go module + gimme to manage hugo instead of amd64 only third party docker image, don't require docker, run in host network etc.

### CODE REVIEW

**Comment by BenTheElder** [comment]
Rendered: https://deploy-preview-3232--k8s-kind.netlify.app/

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Comment by zloom** [comment]
Thanks for removing this banner, glad to see the codebase stay neutral.

**Pull request merged**
