### PR TITLE
add ability to enable kubelet structured logging in CI

### PR DESCRIPTION
**Pull request by BenTheElder**
we can add another kubernetes periodic CI job with: `KUBELET_LOG_FORMAT=structured`

/cc @ehashman @dims

### CODE REVIEW

**Review by ehashman — COMMENTED** [review]
/lgtm

**Comment by ehashman** [comment]
ref https://github.com/kubernetes/kubernetes/issues/99802

**Comment by BenTheElder** [comment]
hmm we're still having some github actions flakes as well. need to get some time to look into these.

**Pull request merged**
