### PR TITLE
update to containerd v1.5.5

### PR DESCRIPTION
**Pull request by BenTheElder**
previously we were at a pre-release version to pick up the runc change

### CODE REVIEW

**Comment by aojea** [comment]
4 hours ago, you are fast
/lgtm

**Review by amwat — COMMENTED** [review]
/lgtm

**Comment by BenTheElder** [comment]
I've been waiting for runc v1.0.1 to land, they announced on twitter at release and I prodded our nightly build :-)

**Comment by BenTheElder** [comment]
> Kubernetes e2e suite: [sig-apps] StatefulSet Basic StatefulSet functionality [StatefulSetBasic] should provide basic identity

eh.

**Pull request merged**
