### PR TITLE
feat(docker/provider): defer to desktop.docker.io label for api endpoint, if present

### PR DESCRIPTION
**Pull request by vdice**
* For the Docker provider, adds logic to defer to the `docker.desktop.io/ports/6443/tcp` label value for determining the API server endpoint

Proposed fix for https://github.com/kubernetes-sigs/kind/issues/1732 (also reference this issue for background context)

### CODE REVIEW

**Comment by BenTheElder** [comment]
I think we could do this with one call but it might be a little gross and can be sorted out in a follow-up.

I plan to rewrite the bootstrapping logic to retain more information and abstract things out less internally anyhow, so it's  perhaps not worth it.

**Comment by BenTheElder** [comment]
thank you!

**Comment by vdice** [comment]
> I think we could do this with one call

Ah yes, good idea... all via an extended go template?  Will defer to you, but sounds like perhaps a follow-up and/or rework is currently the favored option.

**Comment by vdice** [comment]
I'm having trouble parsing the test failure(s), but able/ready to address if pointers can be provided.  Thanks!

**Comment by BenTheElder** [comment]
CI / Kubernetes test issues, they're not related to your PR, don't worry about it, sorry about that! :sweat_smile: 

let's get this in as-is
/override pull-kind-e2e-kubernetes

**Pull request merged**
