### PR TITLE
Fixed install command on index and readme.

### PR DESCRIPTION
**Pull request by KrisJohnstone**
#2351 Missed a few places that the go get command should prolly be removed from. Rather then omit go get completely I've  just stolen the text from the quick-install and adapted what is already there.

### CODE REVIEW

**Comment by KrisJohnstone** [comment]
/assign @bentheelder

There's no testing required as it's a text change.

**Review by tao12345666333 — COMMENTED** [review]
/lgtm

**Comment by stmcginnis** [comment]
/lgtm

Is the mismatch between the Linux Foundation CLA check and the EasyCLA check a known thing?

**Comment by BenTheElder** [comment]
> Is the mismatch between the Linux Foundation CLA check and the EasyCLA check a known thing?


They are two separate systems. It's possible OP signed up on the new system (EasyCLA) but not the old. Kubernetes has not migrated to the new yet because it still has issues, but it is enabled in a non-blocking fashion to surface those issues.

This PR still needs to pass the old cla/linuxfoundation check in order to merge. You can see at the bottom of the page that it is marked `Required` in GitHub.

https://groups.google.com/g/kubernetes-dev/c/zdTYKb8VQgo/m/9U-PHB82CAAJ
https://groups.google.com/g/kubernetes-dev/c/-mdBNXLYZ_Y

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

thank you :-)

can you please sign the CLA with the cla/linuxfoundation system? the entire Kubernetes project requires this and unfortunately we cannot merge PRs that do not pass this check.

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

thank you :-)

can you please sign the CLA with the cla/linuxfoundation system? the entire Kubernetes project requires this and unfortunately we cannot merge PRs that do not pass this check.

**Comment by KrisJohnstone** [comment]
Sorry thought I had. I've followed the guide so hopefully it works now.

**Pull request merged**
