### PR TITLE
install open-iscsi

### PR DESCRIPTION
**Pull request by fukuta-tatsuya-intec**
It is one of the most famous network storage implement.

#1548 NFS is already supported.

### CODE REVIEW

**Comment by aojea** [comment]
we try to keep the images lean, nfs is the simplest shared storage with multiple of examples on how to use use it for volume provisioning ... 
is there any argument/use case to consider open-iscsi to be installed by default?

**Comment by fukuta-tatsuya-intec** [comment]
Thanks for the comment. I respect the contributor's policy. (try to keep the images lean)
I sent this pr because of iscsi's fast file transfer rate. 
Our test data is 10GB, which is vast. Faster file transfer speed will increase our testing efficiency.

Tip: The open-iscsi installation has a disk impact of about 15 MB.
```bash
# apt install open-iscsi
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  busybox-initramfs cpio finalrd initramfs-tools-bin initramfs-tools-core klibc-utils kmod libisns0 libklibc libkmod2 libopeniscsiusr netbase udev zstd
Suggested packages:
  libarchive1 bash-completion
The following NEW packages will be installed:
  busybox-initramfs cpio finalrd initramfs-tools-bin initramfs-tools-core klibc-utils kmod libisns0 libklibc libkmod2 libopeniscsiusr netbase open-iscsi udev
  zstd
0 upgraded, 15 newly installed, 0 to remove and 0 not upgraded.
Need to get 3278 kB of archives.
After this operation, 15.6 MB of additional disk space will be used.
```

Your Respectfully

**Comment by aojea** [comment]
> Our test data is 10GB, which is vast. Faster file transfer speed will increase our testing efficiency.

It's hard for us add more dependencies without a general use case, however, you can always create and maintain your own images, just create Dockerfile with the kind image as based and install the openiscsi dependency

```
FROM kindest/node:1.25

RUN echo "Installing Packages ..." \
    && DEBIAN_FRONTEND=noninteractive clean-install \
    open-iscsi  
```

**Comment by BenTheElder** [comment]
I'm not familiar with iscsi but enabling a [built-in](https://kubernetes.io/docs/concepts/storage/volumes/#iscsi) vendor-neutral remote storage type seems reasonable for < 16MB on-disk.

**Review by BenTheElder — COMMENTED** [review]
/ok-to-test
/lgtm
/approve
rebased + updated base image

**Comment by BenTheElder** [comment]
s390x build flake again
/retest

**Pull request merged**
