### PR TITLE
version pre release is always true

### PR DESCRIPTION
**Pull request by converge**
Signed-off-by: João Vanzuita <joaovanzuita@me.com>

### CODE REVIEW

**Comment by aojea** [comment]
Is it?

**Comment by converge** [comment]
> Is it?

this is my very first PR to the project, pls correct me if I'm wrong. 

the condition checks if the constant value is != than "", the constant cannot be changed via LDFLAGS since only "var" are able to be updated during build time. 

reference: https://github.com/kubernetes-sigs/kind/blob/main/pkg/cmd/kind/version/version.go#L61

**Comment by aojea** [comment]
yeah, it does, @BenTheElder knows how this works better and he may expand on this, but the constant is modified manually for the releases,. see https://github.com/kubernetes-sigs/kind/commit/d39dfa08bf2aba2a0e4f3fb51fa715147d299b84

**Comment by converge** [comment]
> yeah, it does, @BenTheElder knows how this works better and he may expand on this, but the constant is modified manually for the releases,. see [d39dfa0](https://github.com/kubernetes-sigs/kind/commit/d39dfa08bf2aba2a0e4f3fb51fa715147d299b84)

I see.. there is also a script to update the version https://github.com/kubernetes-sigs/kind/blob/9ad13414051cf9f7b731f7213c456815b6ed3ade/hack/release/create.sh#L49

I'll close this PR.

**Comment by BenTheElder** [comment]
It's done this way so that "go get" produces the right thing with release tags at least.

**Pull request closed without merging**
