### PR TITLE
upgrade to containerd 1.3.4

### PR DESCRIPTION
**Pull request by BenTheElder**
let's try this again

### CODE REVIEW

**Comment by BenTheElder** [comment]
[1.12 kubectl run test flake](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_kind/1511/pull-kind-conformance-parallel-1-12/1253980081013919746/). Ran quickly.
/retest

**Comment by BenTheElder** [comment]
[1.14 kubectl run flake ...](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_kind/1511/pull-kind-conformance-parallel-1-14/1253980081013919745/) in 26m
[master projected secret optional updates flake](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kind/1511/pull-kind-e2e-kubernetes/1253980081013919748) in 26m
/retest

**Comment by BenTheElder** [comment]
[1.16 statefulset flake](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_kind/1511/pull-kind-conformance-parallel-1-16/1253980081013919744/) in 30m
/retest

**Comment by BenTheElder** [comment]
[1.16 kubectl run flake](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_kind/1511/pull-kind-conformance-parallel-1-16/1253991405613748232/) in 23m

**Comment by aojea** [comment]
do you want to upgrade cri-tools too? 
or should be done in a follow up PR? 
https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.18.0

**Comment by BenTheElder** [comment]
I would also like to upgrade that (and other things) but my first goal is to see if we're blocked on upgrading containerd for some reason. so far this already smells somewhat flakier.

**Comment by BenTheElder** [comment]
[master ... ran out of time, all tests passing otherwise](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kind/1511/pull-kind-e2e-kubernetes/1253988134069211137) 40m
/retest

**Comment by BenTheElder** [comment]
https://github.com/kind-ci/containerd-nightlies/releases/tag/containerd-1.3.3-61-g60bc1282
this one does not have the golang upgrade, however it is nearly the same as 1.3.4 https://github.com/containerd/containerd/compare/60bc1282...v1.3.4

going to throw another PR at CI to compare

**Comment by BenTheElder** [comment]
all but master have passed now, but not without flakes

**Comment by aojea** [comment]
:/ timed out pull-kind-e2e-kubernetes — Job failed.

/test all

**Comment by BenTheElder** [comment]
the diff between this and the other PR is very small, I increasingly suspect a golang related problem

**Comment by BenTheElder** [comment]
possibly related issues to investigate:
https://github.com/containerd/cri/issues/1427
https://github.com/containerd/containerd/pull/4204
https://github.com/kubernetes/kubernetes/issues/89064

**Comment by BenTheElder** [comment]
https://github.com/containerd/containerd/issues/4068 is observed in one of the failures

**Comment by BenTheElder** [comment]
CI should be minimally busy right now I think...
/test all

**Comment by BenTheElder** [comment]
/test all
we're going to want fixes from HEAD though https://github.com/containerd/containerd/issues/4020
https://github.com/containerd/containerd/pull/4214

**Pull request closed without merging**
