### PR TITLE
don't symlink /dev/console to /dev/kmsg

### PR DESCRIPTION
**Pull request by BenTheElder**
see https://github.com/kubernetes-sigs/kind/issues/662#issuecomment-1238911235

### CODE REVIEW

**Comment by aojea** [comment]
is a kernel issue then?

**Comment by BenTheElder** [comment]
> is a kernel issue then?

See the linked discussion for more but TLDR ...

They're not the same and systemd can reject this bogus symlink. lxc removed the option to do this, and the lxc option was the original justification for this being a reasonable solution.

We could instead fake out a file, but I think this is only in environments like LXC where the user can instead ensure the LXC environment has a placeholder.

**Comment by BenTheElder** [comment]
we should do this after https://github.com/kubernetes-sigs/kind/pull/2905

**Comment by BenTheElder** [comment]
not only is this a simplification, the previous change was incorrect.

if we see substantial issues with this, and those environments cannot be fixed, we can consider instead creating a fake file.

but I think this complexity belongs in these unusual, broken environments.

**Comment by BenTheElder** [comment]
one more base image change to pickup before #2933 + v0.16.0 ... containerd 1.6.8

**Pull request merged**
