### PR TITLE
bump to go 1.14.4

### PR DESCRIPTION
**Pull request by BenTheElder**

### CODE REVIEW

**Comment by MHBauer** [comment]
I take it 1.14.4 came out and we're waiting for the dockerhub image?

**Comment by BenTheElder** [comment]
yeah, kind will be able to move forward once the image is ready, kubernetes
has some extra steps after that ...
tempted to build our own, but hasn't been worth it, _yet_

**Comment by aojea** [comment]
/retest
/lgtm
/hold
so you don't have to wait for a lgtm

**Pull request merged**
