### PR TITLE
export logs kind version

### LINKED ISSUE #1850: export logs: add kind version
**What would you like to be added**:

`export logs` adds a `kubernetes-version.txt` with the Kubernetes version. It could be nice to add a `kind-version.txt` with the version of kind.

**Why is this needed**:

Can be useful to debug in some scenarios. This is not really a major issue at all though, very low priority.

### PR DESCRIPTION
**Pull request by kensipe**
Resolves #1850 in a way that is consistent with existing code

Signed-off-by: Ken Sipe <kensipe@gmail.com>

### CODE REVIEW

**Comment by BenTheElder** [comment]
Thanks for the PR!

This should be implemented somewhere else, we want it to happen for all of the node providers (docker,podman,...)

**Comment by kensipe** [comment]
@BenTheElder I took your todo comment as the place to perform the action.   does it make sense to move it to align with the creation of kubernetes-version.txt?     that was my initial intention before seeing the todo comment.

**Comment by BenTheElder** [comment]
That seems like a good place to put it 👍 
I think this TODO has just been carried over since before there the provider abstraction.

**Comment by BenTheElder** [comment]
we should drop the TODO line and see if it was copied into the podman code and drop it there too if so

**Comment by kensipe** [comment]
@BenTheElder moved to common logs which seems better.   Somewhat dissatisfying to have a cmd import in common/logs.go specifically `"sigs.k8s.io/kind/pkg/cmd/kind/version"`.   let me know if this needs refactoring.  I might need some guidance on preferences here if this is desired.

One alternative was to call `kind` from `kind` which I thought was not preferred.   For clarity

```
		writeToPathFn(
			version.DisplayVersion(),
			filepath.Join(dir, "kind-version.txt"),
		),
```
could be replaced with:
```
		execToPathFn(
			n.Command("kind", "version"),
			"kind-version.txt",
		),
```
This has the advantage of removing the `writeToPathFn` and removed the cmd import... it seems to call out for a value which is known within the process.

**Comment by BenTheElder** [comment]
There's no kind binary on the node to call, and even if there was we want to know the kind version on the host doing the log dumping.

This import is fine.
Please squash these commits and remove the identical TODO from the other (podman) location.

**Comment by kensipe** [comment]
makes sense... you got it!

**Comment by aojea** [comment]
it now logs the kind version inside the nodes,
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kind/1854/pull-kind-e2e-kubernetes-1-18/1306291584945360898/artifacts/logs/kind-worker/kind-version.txt

I would prefer to have it in the root path, same as docker.info, 
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kind/1854/pull-kind-e2e-kubernetes-1-18/1306291584945360898/artifacts/logs/docker-info.txt

but this seems to reduce the duplicate code, so

/lgtm

**Comment by aojea** [comment]
both jobs timed out? 
/retest

**Comment by BenTheElder** [comment]
@aojea we probably want to switch to smoke-test style jobs for older kubernetes releases in the future, still thinking about how best to do that. I asked @amwat to write a proposal for version support policy first.
/override pull-kind-conformance-parallel-1-15

**Comment by BenTheElder** [comment]
/lgtm
/approve
thank you!

**Comment by aojea** [comment]
> @aojea we probably want to switch to smoke-test style jobs for older kubernetes releases in the future, still thinking about how best to do that. I asked @amwat to write a proposal for version support policy first.
> /override pull-kind-conformance-parallel-1-15

what about the github actions?

**Comment by kensipe** [comment]
thanks team!

**Pull request merged**
