### PR TITLE
docs(README): add github actions status badges

### PR DESCRIPTION
**Pull request by R3DRUN3**
Added Github actions status badges to readme, as per documentation best practices.

You can take a look at my forked <a href ="https://github.com/R3DRUN3/kind#readme">repo</a> to inspect the appearance of my edit.

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
this seems like an OK addition.
should these badges be on top of the readme file?

**Comment by R3DRUN3** [comment]
> **this seems like an OK addition. should these badges be on top of the readme file?**

@neolit123 that depends, most of the time you find them under the main title in the readme (# tag).

**Comment by aojea** [comment]
I'm afraid of giving the wrong signal, per example, podman is experimental and is far from be stable and supported ... people checking the badge may get the wrong impression

Those actions are smoke test to check that basic functionality works

**Comment by R3DRUN3** [comment]
"*I'm afraid of giving the wrong signal, per example, podman is experimental and is far from be stable and supported ...* *people checking the badge may get the wrong impression*

*Those actions are smoke test to check that basic functionality works*"

@aojea I understand.
What about leaving only the docker one?

**Comment by R3DRUN3** [comment]
@aojea Ok, it should be good now 👍

**Comment by aojea** [comment]
/lgtm
/approve

Thanks

**Comment by BenTheElder** [comment]
Given most of our CI is not on github actions (it is on [Prow](https://docs.prow.k8s.io/docs/overview/)), this is still somewhat misleading.

We previously opted to drop all of the badges.

**Pull request closed without merging**
