### PR TITLE
[WIP] Fedora 35 debug

### PR DESCRIPTION
**Pull request by BenTheElder**
would prefer to avoid #2525 if we can help it, debugging the fedora 35 issue

### CODE REVIEW

**Comment by aojea** [comment]
have you found something?

**Comment by stmcginnis** [comment]
Is this still needed with https://github.com/kubernetes-sigs/kind/pull/2559?

**Comment by BenTheElder** [comment]
I haven't had time recently, I've been out on bereavement. I would still like to finish getting an understanding of the fedora 35 default filesystem and what we can do to handle the actual root cause instead of enabling a non-standard feature gate and disabling a core feature.

It is important for kind as a project to test default-kubernetes, if in the future CI wanted to go rootless then we have a problem. Plus if we try to change something like this back, it can be a breaking change for users.

This PR is not going to merge, it is just for debugging, like #648, [WIP] prevents the bot from merging it.

**Comment by BenTheElder** [comment]
I still think this is something we need to fix someday so we can use rootless to test kubernetes itself, but I just don't have the time to debug this currently.

**Pull request closed without merging**
