### PR TITLE
Perfect documentations again

### PR DESCRIPTION
**Pull request by yuxiaobo96**
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>

Sorry, I made a mistake to close this pr #868 and can't recover.
So I submit a new pr and add some other typo corrections.

### CODE REVIEW

**Comment by yuxiaobo96** [comment]
@hwdef

**Comment by yuxiaobo96** [comment]
/cc @tao12345666333 

I see that you have approved this pr, but it don't add the approve label.
Please help me approve again.
Thank you.   
:)

**Comment by BenTheElder** [comment]
@yuxiaobo96 http://go.k8s.io/owners explains the approval system a bit

**Comment by BenTheElder** [comment]
also https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process linked from the bot comment about approval

**Pull request merged**
