### PR TITLE
set nofile for loadbalancer

### PR DESCRIPTION
**Pull request by BenTheElder**
fixes https://github.com/kubernetes-sigs/kind/issues/2954

/hold

needs some more testing

### CODE REVIEW

**Comment by dlipovetsky** [comment]
With #3115 merged, we explicitly limit HAProxy maximum concurrent connections. Therefore, I think this change is no longer needed.

Please see the explanation in https://github.com/kubernetes-sigs/kind/issues/2954#issuecomment-1453826595.

**Comment by aojea** [comment]
I'm going to use the haproxy image for the cloud-provider-kind, I think that is better to set a sane default in haproxy config directly

**Comment by BenTheElder** [comment]
thanks!

**Pull request closed without merging**
