### PR TITLE
bump haproxy, kindnetd, local-path, base image

### PR DESCRIPTION
**Pull request by BenTheElder**
bumps all of the images recently updated to their latest builds

### CODE REVIEW

**Comment by BenTheElder** [comment]
might be best to just wait and get all of these re-bumped, there's also a CNI plugins update available and we just changed the builds again for kindnetd and local-path-provisioner in #3214

**Comment by BenTheElder** [comment]
filed https://github.com/kubernetes-sigs/kind/pull/3215

**Comment by aojea** [comment]
is this with the latest images?

**Comment by aojea** [comment]
uh oh

```
stderr:
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "6be0368be0f6208c997a5a4271766e57b99267da6900bdd3ee89acdc2ce9d9b4": OCI runtime exec failed: exec failed: unable to start container process: error adding pid 37543 to cgroups: failed to write 37543: openat2 /sys/fs/cgroup/unified/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-podc9cb3b02_abb6_4dec_baef_3f148adca41f.slice/cri-containerd-8c2d29c232674cfcb3cc6225e1dbcdcf889f8850d1f2b9dfa861fa00982521f8.scope/cgroup.procs: no such file or directory: unknown
```

**Comment by BenTheElder** [comment]
I'm bisecting the changes, locally building just for amd64 and testing which commits work and don.t

5890ae97 works for building an image at least, for me locally actually the containerd teardown at image build time is broken on the image in this PR

**Comment by BenTheElder** [comment]
5890ae97..main only has the distro / cross build change, my current suspicion is the systemd package.

**Comment by BenTheElder** [comment]
With this patch (breaks cross-building but can be built with `make -C images/base quick` just for the host platform)
```diff
diff --git a/images/base/Dockerfile b/images/base/Dockerfile
index 1bb8d929..041182db 100644
--- a/images/base/Dockerfile
+++ b/images/base/Dockerfile
@@ -20,7 +20,7 @@
 # start from ubuntu, this image is reasonably small as a starting point
 # for a kubernetes node image, it doesn't contain much we don't need
 # this stage will install basic files and packages
-ARG BASE_IMAGE=debian:bullseye-slim
+ARG BASE_IMAGE=ubuntu:22.04
 FROM $BASE_IMAGE as base
 
 # copy in static files
@@ -98,10 +98,9 @@ COPY --chmod=0755 scripts/third_party/gimme/gimme /usr/local/bin/
 COPY --chmod=0755 scripts/target-cc /usr/local/bin/
 # tools needed at build-time only
 # first ensure we can install packages for both architectures
-RUN dpkg --add-architecture arm64 && dpkg --add-architecture amd64 \
-    && clean-install bash ca-certificates curl git make pkg-config \
-    crossbuild-essential-amd64 crossbuild-essential-arm64 \
-    libseccomp-dev:amd64 libseccomp-dev:arm64
+RUN clean-install bash ca-certificates curl git make pkg-config \
+    build-essential \
+    libseccomp-dev
 # set by makefile to .go-version
 ARG GO_VERSION
 RUN eval "$(gimme "${GO_VERSION}")" \
 ```
 
 I can build an image and create a cluster. So that points to the distro differences rather than the build process differences.

**Comment by BenTheElder** [comment]
> OCI runtime exec failed: exec failed: unable to start container process: exec: "pkill": executable file not found in $PATH: unknown

ah, well that's a gap ..

**Comment by BenTheElder** [comment]
I think that's it for the breaking change, just the lack of procps, adding procps results in a functioning node image build.

I'm going to do some more checking though.

**Comment by BenTheElder** [comment]
I've rebased this to all updated images following https://github.com/kubernetes-sigs/kind/pull/3218

**Comment by BenTheElder** [comment]
It works for me locally, but my local dev machine is on cgroup v2

**Comment by BenTheElder** [comment]
rebased with #3220

**Pull request merged**
