### PR TITLE
[TESTING IPV6 CI FAILURES] Update CoreDNS config to 1.5 ?

### PR DESCRIPTION
**Pull request by aojea**
Fix current IPv6 CI failures on DNS tests

https://testgrid.k8s.io/conformance-kind#kind%20(IPv6),%20master%20(dev)%20%5Bnon-serial%5D

### CODE REVIEW

**Comment by neolit123** [comment]
/lgtm
xref:
https://github.com/kubernetes/kubernetes/commit/6821d21260e3f7ad6eec0b0e5e8989187ac11794#diff-81c5511bc26ac9a2e5cdf87b9d5da921R317

**Comment by aojea** [comment]
/hold

this is for testing, let's try add it to #786

**Comment by aojea** [comment]
seems related to the new ready plugin

```
Warning  Unhealthy         2m30s (x31 over 7m30s)  kubelet, kind-control-plane  Readiness probe failed: Get http://[fd00:10:244::2]:8181/ready: dial tcp [fd00:10:244::2]:8181: connect: connection refused
  linux-6my5  aojeagarcia   coredns15  …  src  sigs.k8s.io  kind  docker exec -it kind-control-plane bash
root@kind-control-plane:/# curl http://[fd00:10:244::2]:8181/ready
curl: (7) Failed to connect to fd00:10:244::2 port 8181: Connection refused
root@kind-control-plane:/# curl http://[fd00:10:244::2]:8080
404 page not found
root@kind-control-plane:/# curl http://[fd00:10:244::2]:8080/health
OKroot@kind-control-plane:/#
```

**Comment by aojea** [comment]
Ok, I think I've found the issue but don't know what's causing it, I can't reproduce it locally
  
Don't know why the ci is not translating : into -

/errors: 2 fd00:10:244:0:2::40---.dns-1651.pod.cluster.local.c.k8s-prow-builds.internal. A: dial udp 10.63.240.10:53: connect: network is unreachable
2019-08-21T17:40:53.775118315Z stdout F 2019-08-21T17:40:53.774Z [ERROR] plugin/errors: 2 fd00:10:244:0:2::40---.dns-1651.pod.cluster.local.c.k8s-prow-builds.internal. AAAA: dial tcp 10.63.240.10:53: connect: network is unreachable
2

**Comment by aojea** [comment]
is not coredns, is not using the right command to create the queries

```
ï¿½[1mSTEPï¿½[0m: Running these commands on jessie: for i in `seq 1 600`; do check="$$(dig +notcp +noall +answer +search kubernetes.default.svc.cluster.local A kubernetes.default.svc.cluster.local AAAA)" && test -n "$$check" && echo OK > /results/jessie_udp@kubernetes.default.svc.cluster.local;check="$$(dig +tcp +noall +answer +search kubernetes.default.svc.cluster.local A kubernetes.default.svc.cluster.local AAAA)" && test -n "$$check" && echo OK > /results/jessie_tcp@kubernetes.default.svc.cluster.local;podARec=$$(hostname -i| awk -F. '{print $$1"-"$$2"-"$$3"-"$$4".dns-6312.pod.cluster.local"}');check="$$(dig +notcp +noall +answer +search $${podARec} A $${podARec} AAAA)" && test -n "$$check" && echo OK > /results/jessie_udp@PodARecord;check="$$(dig +tcp +noall +answer +search $${podARec} A $${podARec} AAAA)" && test -n "$$check" && echo OK > /results/jessie_tcp@PodARecord;sleep 1; done
```

@neolit123 you know if this function can access this variable in the framework.TextContext?

https://github.com/kubernetes/kubernetes/blob/c008cf95a92c5bbea67aeab6a765d7cb1ac68bd7/test/e2e/network/dns_common.go#L478

**Comment by aojea** [comment]
this fixes the failures https://github.com/kubernetes/kubernetes/pull/81750

**Pull request closed without merging**
