### PR TITLE
Capitalize Command Descriptions

### PR DESCRIPTION
**Pull request by danielhelfand**
Currently, commands/subcommands are not consistent in terms of whether or not the beginning of the description is capitalized. This pull request changes all lower case description beginnings to capitalized. 

This inconsistency also exists for flags, and I would be happy to follow up with something to also correct those flags. Could do that in this pr too if that would be easier.

### CODE REVIEW

**Comment by aojea** [comment]
/test pull-kind-e2e-kubernetes
unrelated failure
thanks LGTM
/assign @BenTheElder

**Comment by BenTheElder** [comment]
/lgtm
/approve
this is consistent with kubectl

**Pull request merged**
