### PR TITLE
Securing many http links to https links

### PR DESCRIPTION
**Pull request by truongnh1992**
Fix http link to https link for security, modify many link
http to https in the project.

Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>

### CODE REVIEW

**Comment by aojea** [comment]
/ok-to-test
/lgtm
Thanks
/assign @BenTheElder

**Comment by BenTheElder** [comment]
failure is https://github.com/kubernetes/test-infra/pull/15829

**Comment by BenTheElder** [comment]
/lgtm
/approve
thanks

**Pull request merged**
