### PR TITLE
doc: fix wrong implementation of creation of kong-ingress

### PR DESCRIPTION
**Pull request by orange-guo**
1. The container proxy is in the deployment proxy-kong.
3. Set the value of replicas in deployment proxy-kong to 1 to ensure the hostPort can be allocated.

### CODE REVIEW

**Comment by aojea** [comment]
@shaneutt any chance you can review or get someone from kong to review this?

**Comment by BenTheElder** [comment]
With some of these we're considering moving to linking out to an upstream guide instead, e.g. https://projectcontour.io/guides/kind/ where it'll be better maintained when there are changes to the ingress application.

**Comment by BenTheElder** [comment]
CLA is unfortunately required to merge anything

**Comment by orange-guo** [comment]
@BenTheElder Hi, The CLA is signed

**Review by shaneutt — APPROVED** [review]

**Review by BenTheElder — APPROVED** [review]

**Pull request merged**
