### PR TITLE
get junit output in tests

### PR DESCRIPTION
**Pull request by BenTheElder**
- use gotestsum to get junit output (the same as what we chose for k/k)
- handle copying to artifacts so it shows up in CI
- filter out `zz_generated.*` in code coverage
- dedupe unit testing in presubmit

### CODE REVIEW

**Comment by BenTheElder** [comment]
need to update the test-infra job...

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kind-unit/1178845969123381256 :tada:

**Comment by aojea** [comment]
impressive

**Pull request merged**
