### PR TITLE
Update to go 1.13rc2

### PR DESCRIPTION
**Pull request by tao12345666333**
Full diff https://github.com/golang/go/compare/go1.13rc1...go1.13rc2

### CODE REVIEW

**Comment by tao12345666333** [comment]
Wait for the golang image be published.

**Comment by neolit123** [comment]
k-sigs/kind should be fine but k/k not, yet.

**Comment by BenTheElder** [comment]
we're already on rc1, but I didn't file this PR yet because I haven't read the changelog yet

**Comment by BenTheElder** [comment]
https://github.com/BenTheElder/kind/tree/113rc2 :^)

**Comment by BenTheElder** [comment]
these images seem to take a surprisingly long time to become available

**Comment by tao12345666333** [comment]
For `kind`, there are no special dependencies in this version (at least I don't see it at the moment).
Keep updating only for 1.13 final release, we can upgrade smoothly.

**Comment by tao12345666333** [comment]
> these images seem to take a surprisingly long time to become available

Yes, the [PR](https://github.com/docker-library/official-images/pull/6556) has been merged. 

Then the offcial image build job will pick up the changes and build and push to the relevant per-architecture repositories. Job detail https://doi-janky.infosiftr.net/job/multiarch/view/images/view/golang/

After all jobs finish, the new job will collects those updates into the true DockerHub repo. https://doi-janky.infosiftr.net/job/put-shared/job/light/

**Comment by BenTheElder** [comment]
Yep I'm fully aware, I periodically help upgrade Kubernetes's usage of that image 🙃 the builders take a while.

**Comment by BenTheElder** [comment]
Seems tide can't merge due to netlify 🤷‍♂️
> tide Not mergeable. Job deploy/netlify has not succeeded.

Since this doesn't change any docs I'll just merge it.

**Pull request merged**
