### PR TITLE
images/base: disable udev.service

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Discussed in https://github.com/kubernetes-sigs/kind/pull/1935#discussion_r533130699

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Failure of Podman CI seems unrelated
```
• Waiting ≤ 1m0s for control-plane = Ready ⏳  ...
 ✓ Waiting ≤ 1m0s for control-plane = Ready ⏳
 • Ready after 28s 💚
ERROR: failed to create cluster: network details should only be one line, got 0 lines
```

**Comment by AkihiroSuda** [comment]
@BenTheElder PTAL

**Comment by BenTheElder** [comment]
podman CI is indeed broken atm (breaking podman changes...) aojea is on it

I took tonight to work on the out of sync contributor guide mostly, I'll
get back to PR review in the morning 😅

**Comment by aojea** [comment]
> podman CI is indeed broken atm (breaking podman changes...) aojea is on it

fixed by https://github.com/kubernetes-sigs/kind/pull/1790

**Comment by BenTheElder** [comment]
fix is merged now, but I'm off to exercise the pup. will review tonight.

also, github actions requires that we rebase this PR to pick up the fix, unlike prow 😞

**Comment by AkihiroSuda** [comment]
thanks, rebased

**Comment by BenTheElder** [comment]
/lgtm
/approve
/hold
(will do follow-up in the morning and get this in)

**Comment by AkihiroSuda** [comment]
ping maintainers

**Comment by aojea** [comment]
@BenTheElder we need to bump the image on https://github.com/kubernetes-sigs/kind/pull/1979/ , so I think we should have this in before that lands

**Comment by BenTheElder** [comment]
I did the bump push. I did not add it to the PR because everything is on hold pending the fact that we seem to have broken kind in github actions.
When we get sufficient time to resolve that we can move with more changes.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/1969 should be resolved, finally 🤞

**Comment by AkihiroSuda** [comment]
rebased

**Pull request merged**
