### PR TITLE
minor nit

### PR DESCRIPTION
**Pull request by BenTheElder**
/shrug
/cc @aojea

### CODE REVIEW

**Comment by BenTheElder** [comment]
xref https://github.com/kubernetes-sigs/kind/pull/1003

**Comment by aojea** [comment]
wow, I didn't mean to address this nit 😅

**Comment by aojea** [comment]
/lgtm

🙃

**Comment by aojea** [comment]
/test pull-kind-conformance-parallel-ipv6

still these errors in kube-proxy 🤔 
```
2019-10-23T20:56:35.955254605Z stderr F E1023 20:56:35.952985       1 proxier.go:728] Failed to ensure that nat chain KUBE-SERVICES exists: error creating chain "KUBE-SERVICES": exit status 4: Another app is currently holding the xtables lock. Stopped waiting after 5s.
2019-10-23T20:56:41.278225711Z stderr F E1023 20:56:41.268575       1 proxier.go:736] Failed to ensure that filter chain OUTPUT jumps to KUBE-SERVICES: error checking rule: exit status 4: Another app is currently holding the xtables lock. Stopped waiting after 5s.
2019-10-23T20:56:46.285383839Z stderr F E1023 20:56:46.281531       1 proxier.go:728] Failed to ensure that filter chain KUBE-EXTERNAL-SERVICES exists: error creating chain "KUBE-EXTERNAL-SERVICES": exit status 4: Another app is currently holding the xtables lock. Stopped waiting after 5s.
2019-10-23T20:56:51.519486821Z stderr F E1023 20:56:51.518097       1 proxier.go:736] Failed to ensure that filter chain INPUT jumps to KUBE-EXTERNAL-SERVICES: error checking rule: exit status 4: Another app is currently holding the xtables lock. Stopped waiting after 5s.
2019-10-23T20:56:56.583522562Z stderr F E1023 20:56:56.579651       1 proxier.go:728] Failed to ensure that filter chain KUBE-EXTERNAL-SERVICES exists: error creating chain "KUBE-EXTERNAL-SERVICES": exit status 4: Another app is currently holding the xtables lock. Stopped waiting after 5s.
2019-10-23T20:57:01.947110687Z stderr F E1023 20:57:01.891393       1 proxier.go:728] Failed to ensure that filter chain KUBE-EXTERNAL-SERVICES exists: error creating chain "KUBE-EXTERNAL-SERVICES": exit status 4: Another app is currently holding the xtables lock. Stopped waiting after 5s.
2019-10-23T20:57:06.985757475Z stderr F E1023 20:57:06.983356       1 proxier.go:728] Failed to ensure that filter chain KUBE-EXTERNAL-SERVICES exists: error creating chain "KUBE-EXTERNAL-SERVICES": exit status 4: Another app is currently holding the xtables lock. Stopped waiting after 5s.
2019-10-23T20:58:02.989752122Z stderr F E1023 20:58:02.989532       1 proxier.go:728] Failed to ensure that filter chain KUBE-EXTERNAL-SERVICES exists: error creating chain "KUBE-EXTERNAL-SERVICES": exit status 4: Another app is currently holding the xtables lock. Stopped waiting after 5s.
```

hope we can merge the iptables-1.8.3 image to see if there is a problem with the iptables versions

**Pull request merged**
