### PR TITLE
upgrade base image + deps, support containerd-fuse-overlayfs in update-shasums

### PR DESCRIPTION
**Pull request by BenTheElder**
https://github.com/containerd/containerd/security/advisories/GHSA-c72p-9xmj-rx3w

### CODE REVIEW

**Comment by BenTheElder** [comment]
No flakes!?

**Comment by aojea** [comment]
> No flakes!?

Dos you expect them?

**Comment by BenTheElder** [comment]
I mean in Kubernetes: always 😂

**Pull request merged**
