### PR TITLE
podman: use devicemapper for some filesystems

### PR DESCRIPTION
**Pull request by aojea**
use the same logic used for docker in podman

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
I was hitting https://github.com/kubernetes-sigs/kind/issues/2524 with Rootless Docker 20.10.10 on Fedora 35 with btrfs.

So this PR doesn't seem enough to fix #2524

**Comment by aojea** [comment]
> I was hitting #2524 with Rootless Docker 20.10.10 on Fedora 35 with btrfs.
> 
> So this PR doesn't seem enough to fix #2524

/hold
indeed

**Comment by aojea** [comment]
/hold cancel

I think that at least is worth to have the same logic in both providers

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
