### PR TITLE
add monitoring to kind

### PR DESCRIPTION
**Pull request by aojea**
Install a prometheus deployment that collect metrics from all
the kubernetes components.
Modify kube-proxy to listen for metrics in all addresses, it listen
by default only in localhost.
Once the cluster is destroyed, it dumps the prometheus snapshot
as a tarball, so it can be analyzed locally.

https://suraj.io/post/how-to-backup-and-restore-prometheus/

### CODE REVIEW

**Comment by aojea** [comment]
/hold
I want to investigate more the CI performance from the cluster POV

**Comment by aojea** [comment]
niiiiiiiiiiiiiiiiiiiiiiiice

image

**Comment by BenTheElder** [comment]
I think we should discuss having a mode where e2e.test in k/k is responsible for installing monitoring and snapshotting it 🤔

**Comment by aojea** [comment]
> I think we should discuss having a mode where e2e.test in k/k is responsible for installing monitoring and snapshotting it

let's fork this to k/k then, I really find it useful in the openshift CI, they do this metrics snapshoting 

> I think we should discuss having a mode where e2e.test in k/k is responsible for installing monitoring and snapshotting it

yeah. let's discuss it there
https://github.com/kubernetes/kubernetes/issues/103145

**Pull request closed without merging**
