### PR TITLE
WIP Add service LoadBalancer to kindnetd

### PR DESCRIPTION
**Pull request by aojea**
I just stumbled onto this https://github.com/elsonrodriguez/minikube-lb-patch/blob/master/main.go
and seems a good addition to kind, especially for CI testing

### CODE REVIEW

**Comment by tao12345666333** [comment]
SGTM 👍

**Comment by aojea** [comment]
@BenTheElder I think that this can be useful but don't know what will be the right place to add it.
I have mixed feelings adding it to kind, maybe as an addon? kindLB?

**Comment by BenTheElder** [comment]
I'm not sure how useful this is tbh. So you just set the LB IP to the in cluster IP?

**Comment by aojea** [comment]
I´m assuming that you are using a test client from the same docker network, using the cluster IP you can reach the services, can't you?

**Comment by BenTheElder** [comment]
No? clusterIP == one of the service IPs IE one of the VIPs by kube-proxy, not the node IPs.

You can only reach these from within the cluster with a typical cluster configuration.

**Comment by aojea** [comment]
you are right, we should have a node ip in linux or localhost in mac-windows

Once I have time will iterate over this, I still think it can be useful for testing applications that use LBs

**Comment by aojea** [comment]
Don't think kindnet should implement this, it can be very easily added as an addon

**Comment by BenTheElder** [comment]
The real problem is that you can't just set it to localhost because localhost is local to each network namespace.

To do this right you have to do something like add an IP on a host interface and bind a listener to that.

**Comment by BenTheElder** [comment]
But also yes, kindnetd might not be the right place for this.

**Pull request closed without merging**
