### PR TITLE
fix incorrect yaml tag in PatchJSON6902

### PR DESCRIPTION
**Pull request by ysz**

### CODE REVIEW

**Comment by aojea** [comment]
:upside_down_face:

**Comment by BenTheElder** [comment]
Hi: thanks for this fix!

Please do not put `Fixes #980` in the commit, this causes some poor behavior in github around forks 😞 
See: https://github.com/kubernetes/test-infra/issues/5032, https://github.com/kubernetes/test-infra/issues/12240 for more context

**Comment by ysz** [comment]
> Please do not put `Fixes #980` in the commit

Fixed.

**Comment by BenTheElder** [comment]
/lgtm
/approve
thank you!

**Pull request merged**
