### PR TITLE
Updating README to point for latest 0.10.0 release

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

Very minor change, basically pointing to the latest version on the central README file.

### CODE REVIEW

**Comment by BenTheElder** [comment]
Thanks for the PR!

Usually when we do this we also update the references in the docs site under site/

I've been hoping for a follow-up to my review on https://github.com/kubernetes-sigs/kind/pull/2032, but I would happily accept a PR bumping the references manually again instead.

Would you mind bumping the rest to match?

**Comment by matzew** [comment]
> Would you mind bumping the rest to match?

sure thing!

**Comment by matzew** [comment]
/refresh

I signed the CLA for Red Hat

**Comment by BenTheElder** [comment]
/ok-to-test
/lgtm
/approve
thank you! much overdue ❤️

**Comment by BenTheElder** [comment]
hmm @aojea podman ivp4 multi-node flake

**Pull request merged**
