### PR TITLE
Update docs for WSL2

### PR DESCRIPTION
**Pull request by sozercan**
Windows 10 build 19041 with WSL2 is officially released. Updating WSL2 docs.

### CODE REVIEW

**Comment by PatrickLang** [comment]
I was going to check this out but @sozercan beat me to it. Thanks!

/lgtm

WSL2 rocks.

**Comment by PatrickLang** [comment]
After running a `echo 1 > /proc/sys/vm/drop_caches` I'm down to <8GB total memory usage for Win10 host + WSL2 :)

**Comment by PatrickLang** [comment]
I was able to run `kind build node-image` and then `kind create cluster --image=...` successfully on my dual core laptop with 16GB RAM while keeping Slack and Edge/Chrome active.

**Comment by PatrickLang** [comment]
I don't know what's up with that failure - looks like issue on bash script side. Ginkgo tests passed:

```


[1m[32mRan 632 of 5098 Specs in 1655.539 seconds[0m
[1m[32mSUCCESS![0m -- [32m[1m632 Passed[0m | [91m[1m0 Failed[0m | [33m[1m0 Pending[0m | [36m[1m4466 Skipped[0m


Ginkgo ran 1 suite in 27m45.347443665s
Test Suite Passed
+ cleanup
+ [ true = true ]
+ kind export logs /logs/artifacts/logs
Exported logs for cluster "kind" to:
/logs/artifacts/logs
+ kind delete cluster
Deleting cluster "kind" ...
+ rm -f _output/bin/e2e.test
+ [ -n /tmp/tmp.UcZHi0WaD9 ]
+ rm -rf /tmp/tmp.UcZHi0WaD9
+ cleanup
+ [[ -n /tmp/tmp.88Mkx4h0nk ]]
+ rm -rf /tmp/tmp.88Mkx4h0nk
wrapper.sh] [EARLY EXIT] Interrupted, entering handler ...
/usr/local/bin/wrapper.sh: line 53: EXIT_VALUE: unbound variable
{"component":"entrypoint","file":"prow/entrypoint/run.go:242","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process gracefully exited before 15m0s grace period","time":"2020-05-29T04:44:51Z"}
```

**Comment by BenTheElder** [comment]
don't worry about CI, I'll bypass it as this is a docs only change, CI is having issues right now

thanks all!

**Pull request merged**
