### PR TITLE
fix todo: remove docs/_index.md, now that we have navigation

### PR DESCRIPTION
**Pull request by pacoxu**
https://kind.sigs.k8s.io/docs/devel/ 404
I think it should be https://kind.sigs.k8s.io/docs/contributing/getting-started/.

### CODE REVIEW

**Comment by stmcginnis** [comment]
Can you navigate to this page from anywhere? I couldn't find it without editing the URL to go directly to https://kind.sigs.k8s.io/docs/

As Ben noted at the top of the file, maybe it makes more sense to just remove this file now?

**Comment by pacoxu** [comment]
> As Ben noted at the top of the file, maybe it makes more sense to just remove this file now?

It makes sense

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve
thanks!

**Pull request merged**
