### PR TITLE
Inject IO / logger

### PR DESCRIPTION
**Pull request by BenTheElder**
To make importing easier and decouple these.

Eliminates the `globals` package 🎉 

We'll probably need some follow up to this, but it's a big step.

### CODE REVIEW

**Comment by aojea** [comment]
can we squash them before merge?

**Comment by BenTheElder** [comment]
sure, I was mostly aiming to make it easier to read, prow can squash on
merge even.

**Comment by BenTheElder** [comment]
prow will squash it now

**Comment by aojea** [comment]
naive question, should we pass the logger as a pointer to avoid issues with concurrency or is safe this way?

**Comment by BenTheElder** [comment]
the logger is concurrent safe, and interfaces are internally pointers.

**Comment by BenTheElder** [comment]
/hold
CI output doesn't seem right.

**Comment by aojea** [comment]
indeed
```
W1105 08:31:31.676] + NUM_NODES=2
W1105 08:31:31.676] + KIND_CREATE_ATTEMPTED=true
W1105 08:31:31.676] + kind create cluster --image=kindest/node:latest --retain --wait=1m -v=3 --config=/workspace/_artifacts/kind-config.yaml
W1105 08:31:32.199] Creating cluster "kind" ...
I1105 08:32:46.379]  â€¢ Ready after 0s ðŸ’š
W1105 08:32:48.164] + run_tests
W1105 08:32:48.165] + [ ipv4 = ipv6 ]
```

**Comment by BenTheElder** [comment]
the problem with this currently is that it won't pick up the flags before errors with arguments, so `-q` isn't respected. investigating options.

**Comment by BenTheElder** [comment]
we're just also handling `-q` / `--quiet` before we even invoke cobra, this is the only robust solution I found that didn't involve replacing cobra.

help output should work correctly.

**Comment by BenTheElder** [comment]
other than squashing this should be fine, I think I'm going to let CI squash it though so you can review just the diff since last time 😅

**Comment by BenTheElder** [comment]
/retest
looks like a flake

**Pull request merged**
