### PR TITLE
remove skip from e2e script

### PR DESCRIPTION
**Pull request by BenTheElder**
/hold

### CODE REVIEW

**Comment by BenTheElder** [comment]
It's not, just serial and focus. Around 1.12 skip was removed from conformance finally.

**Comment by neolit123** [comment]
> Around 1.12 skip was removed from conformance finally.

you mean tests with tags like Alpha, Kubectl, Disruptive were removed?

**Comment by BenTheElder** [comment]
I mean conformance was only supposed to have a focus regex, not a skip, but
it did until 1.12 because some tests managed to get tagged [Conformance]
but also with some of those undersireable tags.

When submitting results we've had to make sure not to include the skip, I
accidentally did when first submitting 1.14

**Pull request merged**
