### PR TITLE
Add known issue "Docker Desktop for macOS and Windows"

### PR DESCRIPTION
**Pull request by cavokz**

### CODE REVIEW

**Comment by BenTheElder** [comment]
Thanks for the PR!

We should consider how to reconcile with https://kind.sigs.k8s.io/docs/user/loadbalancer/

**Comment by cavokz** [comment]
> Thanks for the PR!

My pleasure.

> We should consider how to reconcile with https://kind.sigs.k8s.io/docs/user/loadbalancer/

In what sense?

**Comment by BenTheElder** [comment]
There is a fairly detailed note there of the same nature, we should consider if some of that should just be cross referencing this new entry and if any of the text / links should be reused or rewritten to match in either location.

**Comment by aojea** [comment]
/tide squash-merge
/lgtm
/approve

Thanks

**Pull request merged**
