### PR TITLE
match https://github.com/kubernetes-sigs/iptables-wrappers/blob/maste…

### PR DESCRIPTION
**Pull request by BenTheElder**
…r/iptables-wrapper-installer.sh selection logic

see: https://github.com/kubernetes-sigs/kind/issues/2271#issuecomment-850256442

this is one of the only deviations in functionality from the wrapper there.

### CODE REVIEW

**Comment by BenTheElder** [comment]
note: since I haven't bumped the base this doesn't change anything in CI, this is just for review. namely @aojea 🙃

**Comment by aojea** [comment]
yeah, Dan Winship make it work for the case of users that have both rules on the system

**Comment by BenTheElder** [comment]
the logic we had previously was the same as the source at https://github.com/kubernetes/kubernetes/blob/ffe93b3979486feb41a0f85191bdd189cbd56ccc/build/debian-iptables/iptables-wrapper

but that's changed now in https://github.com/kubernetes-sigs/iptables-wrappers/blob/97b01f43a8e8db07840fc4b95e833a37c0d36b12/iptables-wrapper-installer.sh

I haven't checked yet if kube-proxy was also updated

**Comment by aojea** [comment]
> https://github.com/kubernetes/release/blob/0539f9b737ef056d6007b991bd25b92a8706eb7e/images/build/debian-iptables/buster/iptables-wrapper#L28-L38 it has not been updated in kube-proxy

I wonder if that may explain recent bugs open about kube-proxy delays on endpoints :thinking:

**Comment by aojea** [comment]
@danwinship it seems that there are 2 detection modes:

1. # lines legacy > 10
2- # lines legacy > # lines nft

which one do you think is better?
https://github.com/kubernetes-sigs/iptables-wrappers/blob/97b01f43a8e8db07840fc4b95e833a37c0d36b12/iptables-wrapper-installer.sh#L112-L141

**Comment by danwinship** [comment]
The version of the script in the iptables-wrappers repo is best. You ideally want to check `num lines legacy > num lines nft` because that's more accurate, but you don't want to do that if you have the buggy version of iptables-nft that will hang and need to be timed out and killed. So the installer in iptables-wrappers does the good way if you have a good iptables-nft binary, and the less good way if you have a bad binary

**Comment by BenTheElder** [comment]
I filed https://github.com/kubernetes/release/pull/2106 to correct the kube-proxy base image to the second version, we should be on iptables >= 1.8.5 there so we don't need the bug workaround version.

**Comment by BenTheElder** [comment]
This PR also updates kind to that variant.

**Comment by BenTheElder** [comment]
we should push new image(s) anyhow
/hold

**Comment by BenTheElder** [comment]
need to fix https://github.com/kubernetes-sigs/kind/issues/2313 first

**Comment by BenTheElder** [comment]
will rebase on https://github.com/kubernetes-sigs/kind/pull/2320

**Comment by BenTheElder** [comment]
thought we'd be landing other prioritized changes but since we're not yet, rebased this one.

**Comment by BenTheElder** [comment]
re-applying as this is just a rebase

**Pull request merged**
