### PR TITLE
switch to currently supported fedora

### PR DESCRIPTION
**Pull request by BenTheElder**
~stop hardcoding exact download~

xref https://github.com/kubernetes-sigs/kind/pull/3653

/hold

TODO: figure out why fedora 40 isn't working

### CODE REVIEW

**Comment by stmcginnis** [comment]
#3653 is good, but I kind of think it might be good to just make the bigger jump while we're at it.

/lgtm

**Comment by BenTheElder** [comment]
/override pull-kind-e2e-kubernetes-1-29

pod scheduling timeout in prow is not great but also not relevant to this PR

**Comment by BenTheElder** [comment]
So far it looks like booting things is going fine. I notice the actions are off though, we have "docker/docker" ,"nerdctl/nerdctl", "podman/podman" and ... "vm/vm"

that's not related to this PR, but there's clearly a bug in the actions config

**Comment by BenTheElder** [comment]
ohhhh "VM" is cgroup v2 ...

**Comment by BenTheElder** [comment]
at some point we will need cgroup v2 => v1 inversion ...

**Comment by BenTheElder** [comment]
This change isn't working yet.

**Comment by BenTheElder** [comment]
Looks like Fedora 39 works. It's still supported but 40 would be more current.

It also looks like the downloads are slow and we should switch back to downloading from a mirror.

**Comment by stmcginnis** [comment]
Just capturing failure message here for convenience and in case we lose the job logs.

```txt
Pod "pfpod2" is invalid: [spec.containers[0].resources.requests: Invalid value: "600m": must be less than or equal to cpu limit of 500m, spec.containers[0].resources.requests: Invalid value: "600Gi": must be less than or equal to ephemeral-storage limit of 500Gi, spec.containers[0].resources.requests: Invalid value: "600Mi": must be less than or equal to memory limit of 500Mi]
```

**Comment by BenTheElder** [comment]
So that's a bug in the upstream tests and we should file an issue there, it's defintiely not related to this PR which only affects some of the github actions.

**Comment by BenTheElder** [comment]
/override pull-kind-e2e-kubernetes-1-26 pull-kind-e2e-kubernetes-1-27

(prow e2e not relevant for this change)

**Comment by BenTheElder** [comment]
actions are passing, I lost context and I can't see how to pull up older runs easily on github for comparison, so  I'm not sure if the download is _faster_ but it seems sufficiently fast.

**Comment by stmcginnis** [comment]
> actions are passing, I lost context and I can't see how to pull up older runs easily on github for comparison, so I'm not sure if the download is _faster_ but it seems sufficiently fast.

Looking under the Actions tab, I took a look at this and past runs.

The current `VM/CGroupv2` runs took anywhere between 5:37 and 5.51 for the "Boot Fedora" step.

The same jobs with the "e2e-k8s.sh: support --ginkgo.label-filter" PR took between 4:35 and 5:43.

So very slightly more time with the newer Fedora, but that image is probably very slightly larger than the older one anyway. That seems reasonable to me.

/lgtm

**Pull request merged**
