### PR TITLE
test kind config with patches

### PR DESCRIPTION
**Pull request by aojea**
we should try to add unit tests for each bug to cover regressions

### CODE REVIEW

**Comment by BenTheElder** [comment]
> test kind config with patches #985

we actually already test patching with these type of patches, however we don't use namespace as it's deprecated

**Comment by BenTheElder** [comment]
(this is why I didn't rush to write a PR like this :-))

**Comment by aojea** [comment]
we have an awesome community, detected the bug in master and patched it 😍

**Pull request merged**
