### PR TITLE
docs: Add download steps and D4W settings on Windows

### PR DESCRIPTION
**Pull request by PatrickLang**
Added screenshots to show equivalent Docker for Windows settings to those used in Docker for Mac.

### CODE REVIEW

**Comment by aojea** [comment]
just curious, how can I preview the resulting documentation?

**Comment by BenTheElder** [comment]
https://deploy-preview-699--k8s-kind.netlify.com/
@aojea there's a link in the statuses at the bottom of the page

**Comment by aojea** [comment]
/lgtm

thanks @BenTheElder 🙈 😅

**Pull request merged**
