### PR TITLE
Up version to 0.8.1 at quick-start.md

### PR DESCRIPTION
**Pull request by HadesArchitect**

### CODE REVIEW

**Comment by BenTheElder** [comment]
thanks, but unfortunately we're going to need the CLA signed, the organization requires it.

we also need the README.md to match

**Comment by HadesArchitect** [comment]
Thanks @BenTheElder Fixed the main readme.md as well
Signed the CLA, now waiting for the bot to approve it here.

**Comment by BenTheElder** [comment]
thanks!
/ok-to-test

**Comment by BenTheElder** [comment]
/lgtm
/approve
CI is a bit overloaded right now, and this is just a docs change. merging.

**Comment by BenTheElder** [comment]
thank you!

**Pull request merged**
