### PR TITLE
Make rules

### PR DESCRIPTION
**Pull request by BenTheElder**
we need this for a follow-up, where we stop running these shell scripts directly and improve how we build with go.
they're also handy to have.

I moved the shell scripts to make it clearer that they're meant to be run under make now.

/cc @amwat @aojea

### CODE REVIEW

**Comment by BenTheElder** [comment]
we need https://github.com/kubernetes/test-infra/pull/18704 to update CI

**Comment by aojea** [comment]
/lgtm
/hold
so you can unhold when CI get the changes

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kind/1768/pull-kind-verify/1291428015640678401 there we go

**Pull request merged**
