### PR TITLE
WIP: Support for overriding the loadbalancer config for HA clusters

### PR DESCRIPTION
**Pull request by pwittrock**
The load balancing strategy can impact the apiserver performance -- for instance the default loadbalancing approach creates optimistic locking contention on ResourceQuota objects.

### CODE REVIEW

**Comment by pwittrock** [comment]
@BenTheElder LMK if I should file an issue or something.  I didn't see an obvious place to test this.  What would you recommend?

**Comment by aojea** [comment]
what is the goal? replacing default haproxy configuration?

**Comment by pwittrock** [comment]
@aojea

> what is the goal? replacing default haproxy configuration?

Yes, the default haproxy doesn't play nice with ResourceQuota under high-contention.  It would be useful to have more control over how traffic is sent to the apiservers.

**Comment by pwittrock** [comment]
Closing this while I make some updates.

**Pull request closed without merging**
