### PR TITLE
tag 0.1.0 release

### LINKED ISSUE #208: Binary release cadence
Hi folks,

I wrote a blog post on the heels of KubeCon Seattle explaining what KinD is and how it can be used for testing with Kubernetes. I wanted to write a follow-up but wasn't sure if `go get` is still the preferred installation method?

There is a binary 0.1 release but it looks out of date to me vs. master (I may be wrong)

What would you recommend here? It would be ideal if people didn't need go as a pre-req - especially if testing on a minimal VM.

Thanks 👍 

Alex

### PR DESCRIPTION
**Pull request by BenTheElder**
it's time :-)
fixes #208

### CODE REVIEW

**Comment by tao12345666333** [comment]
@BenTheElder  can we add some ci jobs using GitHub API to do this? https://developer.github.com/v3/repos/releases/#create-a-release

we can add one `VERSION` file and make the ci job watch it for release.

**Comment by BenTheElder** [comment]
@tao12345666333 creating a release like that requires referencing a tag (`tag_name`) so I think it won't buy us much. We also still have to push a tag, write the release notes, and post the binaries. I looked at automating more of that but the uploading and tagging part is quick & simple, and automated release notes will not be as good as human curated notes I think :-)

We script (`hack/release/create.sh`):
- updating the version file
- creating the tag
- building binaries for all platforms
- updating the version file again

Manually:
- PR the version file
- Push the tag
- Create a release entry / write release notes, upload the binaries to that

**Comment by BenTheElder** [comment]
we are looking at #197 though for automation of the images, and if we do this more often it will take less time to write the notes hopefully :-)

**Comment by tao12345666333** [comment]
Thanks for your explanation. :+1:

**Comment by neolit123** [comment]
> The current kind Config is now at kind.sigs.k8s.io/v1alpha2, with support for multi-node clusters! (thanks @fabriziopandini!)

we should have outlined that multi-node is enabled on the config side, but not in the backend?

**Comment by BenTheElder** [comment]
@neolit123 multi-node should work (?), but not EG HA, external etcd etc.

**Comment by neolit123** [comment]
hmm, @fabriziopandini could you please comment.
was under the impression that there is still something in the works there.
maybe i should just test myself...

**Comment by BenTheElder** [comment]
There is some in the works, particularly HA related.

**Comment by fabriziopandini** [comment]
@BenTheElder @neolit123 we currently support n>1 workers only.
I will send asap a PR for supporting n>1 control-plane nodes (with external LB) which is P0 for kubeadm, while external-etcd IMO is a lower priority.
And after this IMO we can focus on UX

**Pull request merged**
