### PR TITLE
Add .travis.yml

### PR DESCRIPTION
**Pull request by krichter722**
Easy test of build instructions which allows to detect that their not working (now and in the future after they've been fixed).

### CODE REVIEW

**Comment by krichter722** [comment]
I signed the CLA

**Comment by BenTheElder** [comment]
Thank you, but we already have build CI, every PR builds kind and runs the conformance tests against all supported Kubernetes branches.

You need a supported version of go. https://golang.org/doc/devel/release.html#policy

I'll update the docs to be clear about this.

In the meantime please use the makefile as an alternative that doesn't require a supported go version.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/753 will clarify the go requirements

**Comment by BenTheElder** [comment]
we've clarified this now, hope that helps!
go 1.11+ has modules support, which we need for our dependencies etc. (eg kustomize which is a v3 module)

thanks again though!

**Pull request closed without merging**
