### PR TITLE
node build: Extract version from remote URL

### PR DESCRIPTION
**Pull request by stmcginnis**
At some point changes were made to the structure of the community published tarballs where the expected "version" file is no longer present. This causes the build to fail due to not being able to capture the version of the source being built.

Most of the time the requested version is part of the URL for the remote source anyway. This creates a fallback where the version will be extracted from the URL if it cannot be read explicitly from a "version" file in the tarball content.

This does not cover the local tarball file path, or if the user points to a non-community published URL. But in the "normal" usage of pointing to community published tarballs, this will prevent the node build from failing in the cases where there is not a version file present.

Closes: #3797

### CODE REVIEW

**Comment by BenTheElder** [comment]
> At some point changes were made to the structure of the community published tarballs where the expected "version" file is no longer present. This causes the build to fail due to not being able to capture the version of the source being built.

This is likely a bug in the upstream release process and we should open an issue to discuss this with release engineering.

**Review by BenTheElder — COMMENTED** [review]
This is a breaking change for anyone that was just hosting a tarball at an arbitrary path (versus upstream)

I would really prefer that our release artifacts actually contain the version information in a self-contained way, as a project, and I'm all but certain they did at some point ..

**Comment by stmcginnis** [comment]
> This is a breaking change for anyone that was just hosting a tarball at an arbitrary path (versus upstream)

I don't think this is a breaking change. It will still try to read the version from an included "version" file. If that file is not present, and the URL does not contain a version number in the path, there will be no difference in behavior. I.e., it will still fail, or the version file is present and it will work exactly like it did before.

Agree we need to root cause the artifact issue, but think this could be useful either way.

**Comment by stmcginnis** [comment]
This could be useful as a final fallback if all else fails, but I wasn't aware of the docker_tag available in the source. So looks like https://github.com/kubernetes-sigs/kind/pull/3815 is a good way to go.

**Pull request closed without merging**
