### PR TITLE
remove manpages in clean-install

### PR DESCRIPTION
**Pull request by BenTheElder**
working on revamping the build, broke out this smaller change that shaves at least a MB off the base image

### CODE REVIEW

**Comment by tao12345666333** [comment]
hm, forgot to execute `hack/update-generated.sh`. :laughing:

**Comment by BenTheElder** [comment]
yeah, working on some other changes
/hold

**Comment by BenTheElder** [comment]
whoops, confused which branch I opened the PR with, will re-open with more extensive image changes later.

**Pull request closed without merging**
