### PR TITLE
aggregate masq sync errors

### PR DESCRIPTION
**Pull request by sword-jin**
resolve the TODO, also we should break the loop if context is closed.

### CODE REVIEW

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve
/hold
(holding for @aojea input)

Also @aojea as a TODO should we consider something else in the future, like N *consecutive* failures instead of 3 lifetime errors?

**Comment by BenTheElder** [comment]
thank you!

**Comment by stmcginnis** [comment]
> should we consider something else in the future, like N consecutive failures instead of 3 lifetime errors?

I had the same thought as I started reviewing, but isn't that covered by the else clause:

```go
errs = errs[:0]
```

**Comment by BenTheElder** [comment]
Oh, you're right.
We structured this a little unusually.

**Pull request merged**
