### PR TITLE
Mark Release 0.11

### PR DESCRIPTION
**Pull request by amwat**
ref: https://github.com/kubernetes-sigs/kind/issues/2024

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Not a blocker, but any chance to get this merged in v0.11? https://github.com/kubernetes-sigs/kind/pull/2230 (`make podman resolve short names`)

**Comment by BenTheElder** [comment]
/hold
we are having issues with the cross build on older releases, investigating

> Not a blocker, but any chance to get this merged in v0.11? #2230 (make podman resolve short names)

No, #2230 has outstanding discussion / change in implementation pending.

**Comment by BenTheElder** [comment]
/hold cancel
images were built https://github.com/kubernetes/kubernetes/issues/102087

**Comment by BenTheElder** [comment]
and https://github.com/kubernetes-sigs/kind/pull/2255

**Comment by amwat** [comment]
We should be ready to go here!

**Comment by BenTheElder** [comment]
these needed rebasing, discussed offline, I purged the commits from `main` with a careful force push 😅 

good to try again now.

**Pull request merged**
