### PR TITLE
add config command

### PR DESCRIPTION
**Pull request by yylt**
show config about default cluster

Signed-off-by: yylt <yang8518296@163.com>

### CODE REVIEW

**Comment by aojea** [comment]
naive question, is this really useful?

**Comment by yylt** [comment]
When add  more extra arg about kubernetes components, and I find it's too many parameters which have to set.

should print more args on kubernetes components, but not sure this pr needed, so it's just simple now

**Comment by BenTheElder** [comment]
Hmm, I'm not sure if we want to add this, but if we did it would still be something like `kind [verb] [noun]` for consistency.
In the future it's generally preferable to open an issue to discuss feature additions first so we can discuss that sort of thing up front :sweat_smile:

**Comment by BenTheElder** [comment]
Thanks for the PR but in it's current state we're not going to merge this.
We will need to identify at minimum what the command should be first.
If you'd like to pursue this further, please open an issue with a proposal.

**Pull request closed without merging**
