### PR TITLE
fixes for ppc64le

### PR DESCRIPTION
**Pull request by BenTheElder**
based on https://github.com/kubernetes-sigs/kind/pull/453, but updated after the breaking image changes

FYI @dims @mkumatag

### CODE REVIEW

**Comment by mkumatag** [comment]
@BenTheElder This is great thanks a lot. One minor comment, you may need to sed https://github.com/kubernetes-sigs/kind/blob/master/images/base/Dockerfile#L77 as well

**Comment by BenTheElder** [comment]
ah yes, we should fix that :sweat_smile:

**Pull request merged**
