### PR TITLE
Upgrade containerd 1.6.9

### PR DESCRIPTION
**Pull request by BenTheElder**
containerd has some notable fixes:

> The ninth patch release for containerd 1.6 contains various fixes, reorders the pod setup workflow in the CRI plugin to
prevent CNI resource leaks, and includes a new version of runc.

https://github.com/containerd/containerd/releases/tag/v1.6.9

```console
$ docker run --rm --entrypoint=runc docker.io/kindest/base:v20221025-014d1502 --version
runc version 1.1.4
commit: v1.1.4-0-g5fd4c4d1
spec: 1.0.2-dev
go: go1.18.7
libseccomp: 2.5.1
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Comment by BenTheElder** [comment]
/hold
we should do a new node image and make sure there's nothing surprising in rootless etc.

**Comment by BenTheElder** [comment]
doing that now

**Comment by BenTheElder** [comment]
CI all good

**Pull request merged**
