### PR TITLE
doc: reorganize docs

### PR DESCRIPTION
**Pull request by tao12345666333**
Now only the structure has been adjusted.

If this structure is OK, then update the content (may use other PR to complete)

### CODE REVIEW

**Comment by tao12345666333** [comment]
https://deploy-preview-671--k8s-kind.netlify.com/

**Comment by aojea** [comment]
Sgtm

My only concern is if the advanced features section starts to grow again, how should we reorganize in that case?

**Comment by tao12345666333** [comment]
In my opinion, when advanced features grow to a certain size, I will choose to classify them by function. Such as cluster configuration, debugging, images etc.

**Comment by tao12345666333** [comment]
rebase from HEAD.

**Comment by tao12345666333** [comment]
@BenTheElder PTAL :smile_cat: 

If this change applies, I want to merge it in as soon as possible and start to improve the documentation. (now every time there is a document-related PR merge it needs to re-rebase it :crying_cat_face: )

**Comment by tao12345666333** [comment]
I will resolve conflicts.

**Comment by BenTheElder** [comment]
As discussed in the issue let's roll forward with leaving the current user guide but writing guides for new topics (eg perhaps a guide for using an ingress)

Thanks again for all your contributions!

**Pull request closed without merging**
