### PR TITLE
update storageclass annotation to GA

### PR DESCRIPTION
**Pull request by BenTheElder**
fixes https://github.com/kubernetes-sigs/kind/issues/1017

also removes a pointless annotation from upstream

### CODE REVIEW

**Comment by aojea** [comment]
is this backward compatible?

**Comment by aojea** [comment]
/lgtm
1.13 
https://github.com/kubernetes/kubernetes/pull/68345/commits/f167413661347e399cc7a2b2b89910a5a744833d

**Comment by BenTheElder** [comment]
not 1.13, 1.13 is when the addons were updated, the actual annotation was https://github.com/kubernetes/kubernetes/commit/3beee8da90c19ef4ee99367c9823ba48ecd36a06 which was in v1.7 ... long before kind

**Comment by BenTheElder** [comment]
we just cargo culted the entire storage class from the addons which hadn't been updated because the beta annotation is still supported.

**Pull request merged**
