### PR TITLE
bump cni version to 0.8.6

### PR DESCRIPTION
**Pull request by aojea**
some bug fixes that may help
https://github.com/containernetworking/plugins/releases/tag/v0.8.6

### CODE REVIEW

**Comment by BenTheElder** [comment]
:eyes:

**Comment by aojea** [comment]
> did you notice the PR number is also **86? 🙃

/magic
/destiny
🤙

**Comment by BenTheElder** [comment]
guessing that's just the flakes we've been seeing but less comfortable bypassing on this change

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/17593 is why CI failed this go round

**Pull request merged**
