### PR TITLE
use switch case in DetectNodeProvider

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>

use switch case in DetectNodeProvider

### CODE REVIEW

**Comment by yxxhero** [comment]
@aojea ping

**Review by BenTheElder — COMMENTED** [review]
What improvement is this change expected to bring?

I think this is less clear than the original code, which explicitly checks in a particular order (and should continue to do so for backwards compatibility).

**Comment by yxxhero** [comment]
@BenTheElder 
1.I think multi branch is clearer, and the priority is from top to bottom
2.It is convenient to add more nodeproviders and reduce repeated if
3.This code has no compatibility problem and is backward compatible

WDTF?

**Comment by BenTheElder** [comment]
1. I don't think this is any clearer than imperative if { return}.

2.  I don't expect to be adding many (realistically any in the immediate future) providers anyhow, but also it is not really any less typing.

3. The key part -- Yes, but I think it is less obvious once switching to switch that the ordering must be preserved by future PRs to this code. Switch case is typically used for exhaustive-ness with ordering as an afterthought, bit these method calls are not necessarily mutually exclusive.

**Comment by yxxhero** [comment]
@BenTheElder 
ok. I think you are right. Thanks for your reply.

**Pull request closed without merging**
