### PR TITLE
Adding one more related project

### PR DESCRIPTION
**Pull request by mitar**

### CODE REVIEW

**Comment by BenTheElder** [comment]
will also need to capture in https://github.com/kubernetes-sigs/kind/pull/268.

**Comment by BenTheElder** [comment]
[manual merge due to netlify failure blocking the robot, xref #268]

**Comment by mitar** [comment]
If you are reordering things in #268 I would suggest this one in this PR is also put towards the top because it is very aligned/similar to this project as well.

**Comment by BenTheElder** [comment]
ordering in #268 is based on visual length, otherwise kubeadm-dind-cluster
would be at the top as the closest, what I meant by capturing it there is
also in the site since that copies from the readme.

**Pull request merged**
