### PR TITLE
switch to go 1.15rc1

### PR DESCRIPTION
**Pull request by BenTheElder**

### CODE REVIEW

**Comment by BenTheElder** [comment]
really tempted to switch us to something like https://github.com/syndbg/goenv

@justaugustus did you wind up looking into that for k/k?

**Comment by BenTheElder** [comment]
our friend` [sig-cli] Kubectl client Simple pod should support inline execution and attach `
/retest

**Comment by BenTheElder** [comment]
TBR
going to start soaking this alongside k/k

**Comment by aojea** [comment]
wow, is not risky using rcs?

**Comment by BenTheElder** [comment]
no, rc1 is used by all of google internally for example.
kubernetes is working on making the same switch

**Comment by dims** [comment]
See notes [here](https://github.com/golang/go/wiki/Go-Release-Cycle) @aojea : 

```
One of the criteria for issuing a release candidate is that Google be using that version of the code for new production builds by default: if we at Google are not willing to run it for production use, we shouldn't be asking others to. We may issue the release candidate a few days in advance of Google changing over, depending on how the calendar falls. For example, the change inside Google makes more sense to do on Mondays, so we may issue the release candidate the Wednesday before or the Wednesday after Google converts to the new release by default.
```

**Comment by aojea** [comment]
There is not better test that running things in production :smile
Great

**Pull request merged**
