### PR TITLE
promote stmcginnis to reviwer

### PR DESCRIPTION
**Pull request by BenTheElder**
Sean has been doing a lot of review and support work for some time now, we spoke and I'm proposing him as an official reviewer.

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
LGTM thanks @stmcginnis

**Comment by aojea** [comment]
+1

**Comment by aojea** [comment]
/lgtm

Thanks for all the hard work Sean

**Comment by stmcginnis** [comment]
Thanks everyone - glad to be able to help! 🎉

**Comment by dims** [comment]
thanks @stmcginnis !

**Pull request merged**
