### PR TITLE
correct baseURL, set favicon

### PR DESCRIPTION
**Pull request by BenTheElder**
:tada:

### CODE REVIEW

**Comment by BenTheElder** [comment]
https://deploy-preview-294--kindocs.netlify.com/

**Comment by BenTheElder** [comment]
https://deploy-preview-294--k8s-kind.netlify.com/

**Comment by Katharine** [comment]
Seems legit.

/lgtm

**Comment by BenTheElder** [comment]
/hold cancel
rewrote to use `{{ "url/foo.bar" | relURL}}` or `{{.Site.BaseURL}}` everywhere.

**Pull request merged**
