### PR TITLE
initial netlify + hugo setup

### PR DESCRIPTION
**Pull request by BenTheElder**
This is extremely minimal and rough -- I opted to start by borrowing a few ideas from my past experience with hugo just to get something rough up and running.

EDIT: once the netlify preview is working I will add some more CSS, meta-docs, etc.

### CODE REVIEW

**Comment by BenTheElder** [comment]
https://5c593f55b217340008f75190--kindocs.netlify.com/ :-)
no navigation, no styles, not much of a landing page, but it's rendering the markdown and generally working.

will iterate on fixing some of that first.

**Comment by neolit123** [comment]
like i've mentioned on zoom it seems kind of strange (overkill) to use hugo/netlify and a separate website for kind. test-infra or k/community don't have one, but maybe they should too.

let me know when you need a LGTM here.

**Comment by BenTheElder** [comment]
> test-infra or k/community don't have one, but maybe they should too.

contributor.k8s.io is going to be a thing ~ for k/community.

I also would like to figure out docs for Prow at least sometime after this.

It may be slightly overkill, but everywhere I've found really good docs a site generator is being used to automate things and give better navigation / discoverability, and not all of our content can go on the main site.

The power should be a little more clear once we get the template in shape and more content. The actual content writing will be roughly the same amount of effort.

**Comment by BenTheElder** [comment]
kind should have really good docs for all of:
- quick overview
- usage & scenarios
- library usage
- development / contributing
- design details
- roadmap

We're headed that way, but I think we can push the quality higher 😅

**Comment by BenTheElder** [comment]
rendered: https://deploy-preview-268--kindocs.netlify.com/

still hacking on this intermittently between some other work, but it's coming along.
in particular see: https://deploy-preview-268--kindocs.netlify.com/docs/

the markdown rendering is pretty good now. will look at navigation and a footer later.

**Comment by neolit123** [comment]
awesome, looks good.
will have a more detailed look at the diff tomorrow!

/assign

**Comment by BenTheElder** [comment]
Thanks! Apologies for the huge diff, had to move everything around to bootstrap and I've had to fix some links etc. in addition to the actual hugo / netlify configs.

**Comment by munnerz** [comment]
Added tide/squash label 😄 

/lgtm

**Comment by lbrpsoftware** [comment]
What do you think about Notion?
They are working on it!
I don't know a faster way to EDIT

**Comment by lbrpsoftware** [comment]
A little quick DEMO
I'm not Notion, just think it's great!
Specially the new [GitHub ](https://send.bitwarden.com/#4vSc0E5AeUCc7K8LAYZiZA/JPBrfQyF7oirLUspFe_y9Q)connection!

**Comment by lbrpsoftware** [comment]
skiddy

**Pull request merged**
