### PR TITLE
use files first to resolve dns on node images

### PR DESCRIPTION
**Pull request by aojea**
change back nsswitch.conf to use files first to resolve dns

Fixes: https://github.com/kubernetes-sigs/kind/issues/1723

### CODE REVIEW

**Comment by aojea** [comment]
/hold

let's see first how is working the new image

**Comment by BenTheElder** [comment]
do you remember why we actually did this before? seems like we must have had a reason 😱

**Comment by BenTheElder** [comment]
I'm usually running around doing this and not the opposite like before

**Comment by BenTheElder** [comment]
Intend to double check thoroughly and ship later this weekend.

**Comment by BenTheElder** [comment]
/retest
sheesh pod pending timeouts w/ prow ...

**Comment by BenTheElder** [comment]
flake
/retest

**Pull request merged**
