### PR TITLE
add podman ci

### PR DESCRIPTION
**Pull request by aojea**
add basic ci to test that kind can create clusters with podman as provider.

It can be improved to:
- run e2e tests
- ...
xref: #1778

### CODE REVIEW

**Comment by neolit123** [comment]
IIRC, one downside of actions is that there is no way to retest them by regular contributors without merge access in a repository.

**Comment by aojea** [comment]
> why not run the multi node variants only?

multinode supersedes single node but are harder to debug, also this multinodes exercise HA that adds another layer of complexity with the load balancer

> IIRC, one downside of actions is that there is no way to retest them by regular contributors without merge access in a repository.

I had to go deep into actions lately, and the good thing is that they run on forks, so contributors can test their PR in their forks, this line allows to run the tests manually choosing a branch
https://github.com/kubernetes-sigs/kind/pull/1781/files#diff-4efd11c22b7577e551fe0058f6f7ed81R4

**Comment by neolit123** [comment]
> I had to go deep into actions lately, and the good thing is that they run on forks, so contributors can test their PR in their forks, this line allows to run the tests manually choosing a branch

that is a win, for sure.

**Comment by aojea** [comment]
/retest
pvc test

**Comment by BenTheElder** [comment]
Do we need to do anything on the repo to enable this?

**Comment by aojea** [comment]
/hold
Will enable only the working jobs

I don't thinking we need anything, I already see an actions tab in the repo, but I don't know if there are additional steps, it always worked for me

**Comment by aojea** [comment]
/hold cancel
it seems that is enabled by default but it may be disabled per org and repo
https://docs.github.com/en/actions/getting-started-with-github-actions/about-github-actions#disabling-or-limiting-github-actions-for-your-repository-or-organization

**Comment by BenTheElder** [comment]
Odd...
/retest

**Pull request merged**
