### PR TITLE
Update client-go to v12.0.0

### PR DESCRIPTION
**Pull request by shaneutt**
Resolves https://github.com/kubernetes-sigs/kind/issues/732

### CODE REVIEW

**Comment by aojea** [comment]
@BenTheElder it seems there are some PR updating go dependencies, should we aggregate all of them in one?

**Comment by BenTheElder** [comment]
so I did some digging and actually we're only even importing client-go in the main module in order to get the homedir package which is pretty silly, we can just mimic that behavior and drop that dependency.

/assign

will tackle after https://github.com/kubernetes-sigs/kind/pull/737

**Comment by BenTheElder** [comment]
client-go is now only an indirect dependency by way of kustomize and in such a way that it is not tracked in go.mod after https://github.com/kubernetes-sigs/kind/pull/744

I beleive that should replace this, please rebase and reopen if not.

Thanks for the PR!

**Comment by BenTheElder** [comment]
client-go is now only an indirect dependency by way of kustomize and in such a way that it is not tracked in go.mod after https://github.com/kubernetes-sigs/kind/pull/744

I beleive that should replace this, please rebase and reopen if not.

Thanks for the PR!

**Pull request closed without merging**
