### PR TITLE
bump go to 1.15.5

### PR DESCRIPTION
**Pull request by BenTheElder**

### CODE REVIEW

**Comment by aojea** [comment]
/lgtm
what happen? it was close to the previous one

**Comment by BenTheElder** [comment]
security release, but as a general rule kind just keeps up with latest where possible regardless.

**Comment by aojea** [comment]
was lazy to go to the release notes :)

**Comment by BenTheElder** [comment]
/retest
TLDR some nasty security bugs that mostly shouldn't apply to our usage _currently_, but all the same upgrading.

**Pull request merged**
