### PR TITLE
Updated link to docs in OWNERS file

### PR DESCRIPTION
**Pull request by rlenferink**

### CODE REVIEW

**Comment by alejandrox1** [comment]
/lgtm 
:+1:

**Comment by rlenferink** [comment]
netlify/kindocs/deploy-preview returns 

```text
7:47:53 PM: Error: Unable to locate Config file. Perhaps you need to create a new site.
7:47:53 PM:        Run `hugo help new` for details. (Unsupported Config Type "")
```

Any advice?

**Comment by BenTheElder** [comment]
that's due to netlify being on for #268 but not having been merged yet.

**Comment by BenTheElder** [comment]
i think it will continue to fail unless this PR is rebased, so I'm just going to manually merge.

**Comment by rlenferink** [comment]
Thanks @BenTheElder  !

**Pull request merged**
