### PR TITLE
[HOLD ON UNTIL K/K MERGE] Bump cni version to v0.8.2

### PR DESCRIPTION
**Pull request by aojea**
xref: https://github.com/kubernetes/kubernetes/pull/78819

### CODE REVIEW

**Comment by aojea** [comment]
/hold
we should decide how we want to move with the CNI binaries, kindnet has a strong dependency on them

**Comment by tao12345666333** [comment]
Should we hold this until https://github.com/kubernetes/kubernetes/pull/78819 has been merged?

/lgtm

**Comment by aojea** [comment]
yea, please hold on, seems that CNI 0.8.1 has a bug and they are going to release a new 0.8.2 version

**Comment by BenTheElder** [comment]
Yeah, upstream still has issues with this switch. We'll want to wait for upstream.

**Comment by BenTheElder** [comment]
FYI CI does not build the base image.

**Comment by aojea** [comment]
Thanks @BenTheElder , that explains a lot of things now :sweat_smile:

**Comment by BenTheElder** [comment]
We wound up doing this in a bulk upgrade of all the base image

**Pull request closed without merging**
