### PR TITLE
return IP address using kubeconfig --internal

### PR DESCRIPTION
**Pull request by aojea**
Before 0.8.0 kind get kubeconfig --internal returned the container
IP address of the node with the API server.

Since we added docker custom bridges, the behavior changed
returning the hostname.

We recover the previous behavior returning an IP address, however,
it will return always an IPv4 address.

Fixes: #1558

### CODE REVIEW

**Comment by aojea** [comment]
/assign @BenTheElder 

I'm not super happy but I couldn't find a "clean" way of getting the cluster IP family without adding a new method to the provider or a new variable indicating it.

Totally open to suggestions

**Comment by BenTheElder** [comment]
I don't think most internal clients should use IP still.

**Comment by aojea** [comment]
> I don't think most internal clients should use IP still.
> […](#)

IIRC that the original purpose of the flag was for obtaining the docker IP, it may be used for other containers that do not belong to the cluster.
Internal clients on the nodes can access directly the `/etc/kubernetes/kubeadm.config`

**Comment by aojea** [comment]
adding a new parameter is too gross? 
`--internal (ipv4|ipv6|dns) (default ipv4)`

**Comment by BenTheElder** [comment]
> IIRC that the original purpose of the flag was for obtaining the docker IP, it may be used for other containers that do not belong to the cluster.

no, the purpose of the flag is to obtain a kubeconfig for use inside the cluster network as opposed to the one we export for the host.

wanting it to be an IP instead of whatever the internal default management is is ... different.
it should probably be it's own flag, technically it could apply to the host but probably have a different default (host default to IP to avoid issues where we don't control /etc/hosts, internal default to dns...)

**Comment by BenTheElder** [comment]
btw when I tag an issue `kind/design` that's because we need to design something like this new flag, I wouldn't have tagged a trivial fix this way :upside_down_face: 
I'm not sure what the clearest flags would be.

**Comment by aojea** [comment]
heh my fault, honestly, didn't see the tags and make my mind around it thinking that they only wanted the IPs, let's close and discuss then
/close

**Pull request closed without merging**
