### PR TITLE
optimistically disable dockershim

### PR DESCRIPTION
**Pull request by BenTheElder**
FYI @dims @mattjmcnaughton finally bringing this back

### CODE REVIEW

**Comment by BenTheElder** [comment]
tested locally on 1.19.3

**Comment by BenTheElder** [comment]
creating a new (more optimal) node image from this.

**Comment by BenTheElder** [comment]
/retest
rules_docker flakes https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kind/1932/pull-kind-e2e-kubernetes-1-18/1328988248290103296

**Comment by aojea** [comment]
/lgtm
go go go

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Comment by dims** [comment]
thanks a ton @BenTheElder

**Pull request merged**
