### PR TITLE
docker: detect ip6tables setup failure and fallback to ipv4 only

### PR DESCRIPTION
**Pull request by BenTheElder**
/assign @aojea 
/hold

### CODE REVIEW

**Comment by BenTheElder** [comment]
see: https://github.com/kubernetes-sigs/kind/issues/3677, https://github.com/kubernetes-sigs/kind/issues/3748, ...

**Comment by stmcginnis** [comment]
/lgtm

It's a workaround, but seems like a common enough issue now that it's worth including.

**Comment by aojea** [comment]
/lgtm

the jobs with vagrant are all failing, but does not seem related to this PR

/hold cancel

it stops the bleeding,

**Comment by BenTheElder** [comment]
bypassed broken github actions that seem to be unrelated #3750

**Pull request merged**
