### PR TITLE
fix HA cluster kubeconfig

### PR DESCRIPTION
**Pull request by BenTheElder**
... and fix HA respecting networking config

see https://github.com/kubernetes-sigs/kind/issues/417

### CODE REVIEW

**Comment by BenTheElder** [comment]
cc @tao12345666333, I have not tested this yet but I think this is correct. there was even a TODO 🙃
found and fixed another potential issue with HA while I was at it.

**Comment by tao12345666333** [comment]
thanks for your good job. I will test it ASAP.

**Comment by tao12345666333** [comment]
```
[zhang@localhost kind]$ docker ps -f label=io.k8s.sigs.kind.cluster=ha --format 'table {{ .Names }}\t{{ .P
orts }}'
NAMES                       PORTS
ha-worker2
ha-control-plane            46146/tcp, 127.0.0.1:46146->6443/tcp
ha-control-plane3           42059/tcp, 127.0.0.1:42059->6443/tcp
ha-external-load-balancer   34036/tcp, 127.0.0.1:34036->6443/tcp
ha-control-plane2           39478/tcp, 127.0.0.1:39478->6443/tcp
ha-worker
[zhang@localhost kind]$ kubectl config view                                                               
apiVersion: v1                                                                                            
clusters:                                                                                                 
- cluster:                                                                                                
    certificate-authority-data: DATA+OMITTED                                                              
    server: https://localhost:34036                                                                    
  name: ha                                                                                                
contexts:                                                                                                
- context:                                                                                                
    cluster: ha                                                                                           
    user: kubernetes-admin                                                                                
  name: kubernetes-admin@ha                                                                               
current-context: kubernetes-admin@ha                                                                      
kind: Config                                                                                              
preferences: {}                                                                                           
users:                                                                                                    
- name: kubernetes-admin                                                                                  
  user:                                                                                                   
    client-certificate-data: REDACTED                                                                     
    client-key-data: REDACTED              
```

**Comment by tao12345666333** [comment]
This PR has solved #417 , but I found other issues about HAProxy, I will submit a new issue for tracking. 

Thanks.

**Comment by fabriziopandini** [comment]
/lgtm
Thanks @BenTheElder 
I'm closing https://github.com/kubernetes-sigs/kind/pull/342 due to this PR

**Pull request merged**
