### PR TITLE
HONK

### PR DESCRIPTION
**Pull request by BenTheElder**
add securitygoose warning number 1

Screen Shot 2020-03-09 at 10 13 56 PM

### CODE REVIEW

**Comment by BenTheElder** [comment]
https://deploy-preview-1389--k8s-kind.netlify.com/docs/user/configuration/#api-server

**Comment by amwat** [comment]
https://deploy-preview-1389--k8s-kind.netlify.com/docs/user/configuration/#api-server

/honk

Amazing 😂

**Comment by BenTheElder** [comment]
fixed a typo per `@IanColdwater` 😅

**Comment by BenTheElder** [comment]
/👏👏 @munnerz

**Comment by aojea** [comment]
Hahah super cool

**Pull request merged**
