### PR TITLE
skip preflight and remove Kubernetes < 1.13 workarounds / code

### PR DESCRIPTION
**Pull request by BenTheElder**
This will enable us to control the pause image to match containerd as well (in a future change)

Upstream Kubernetes only supports 1.16+ currently. 1.13 came out December 2018.
1.13+ enables skipping phases, and narrows down the kubeadm config to beta versions only (v1beta1 and v1beta2).
It also enables us to remove some build workarounds related to changes around Kubernetes 1.12.

### CODE REVIEW

**Comment by BenTheElder** [comment]
/retest
pod pending timeout

**Comment by FraBle** [comment]
This might have broken kind for us:
```
Creating cluster "skynet" ...
 ✓ Ensuring node image (kindest/node:v1.13.12) 🖼
 ✓ Preparing nodes 📦 📦 📦 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
 ✗ Joining worker nodes 🚜
ERROR: failed to create cluster: failed to join node with kubeadm: command "docker exec --privileged skynet-worker kubeadm join --config /kind/kubeadm.conf --skip-phases=preflight --v=6" failed with error: exit status 1
Command Output: Error: unknown flag: --skip-phases
```

**Comment by BenTheElder** [comment]
We're currently dropping support for Kubernetes versions without this functionality upstream, it seems this works in single node clusters but not multi-node in 1.13, which was an oversight in the release notes.

It appears that while 1.13 has this flag, it only has it in `kubeadm init` and not `kubeadm join`, whereas 1.14+ has it in both.
I will add a breaking change note to the release notes for now. In the future we may have an alternative workaround.

**Comment by BenTheElder** [comment]
Sorry about that, we should have tested this, shoring up the CI and policy around older versions is something we're looking at this quarter. I've updated the release notes.

Officially the Kubernetes project will not support a release this old, kind supports older releases best-effort currently but only 1.17+ are open for patches / support upstream. https://kubernetes.io/docs/setup/release/version-skew-policy/#:~:text=Supported%20versions&text=The%20Kubernetes%20project%20maintains%20release,9%20months%20of%20patch%20support.

**Pull request merged**
