### PR TITLE
upgrade local-path-provisioner

### PR DESCRIPTION
**Pull request by mweibel**
Upgrades local path provisioner to [v0.0.23](https://github.com/rancher/local-path-provisioner/releases) which, besides other things, introduces the ability to enable shared filesystem support for multi node PVs.

### CODE REVIEW

**Comment by stmcginnis** [comment]
/ok-to-test

I know Ben is pretty busy right now. ;)

**Comment by BenTheElder** [comment]
tests won't actually cover this change, we'll see it in action when the image is built and updated later though

sorry, #3124, https://kubernetes.io/blog/2023/03/10/image-registry-redirect/, and kubernetes code freeze amongst other things have been a bit pressing this week. I had hoped to merge kind outstanding kind fixes (including this update) and get a release out but we'll probably sort out plans for #3124 before releasing so we can potentially switch image hosts in a release before the dockerhub impact.

**Comment by BenTheElder** [comment]
some of the changes from #3124 mean we're at least automating building this image, still following up on making sure those jobs work properly.

**Comment by BenTheElder** [comment]
should get auto-built shortly, iterating on that. then we'll roll this up with the other patches going out shortly.

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kind-push-local-path-provisioner-image/1641301343291314176

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kind-push-local-path-provisioner-image/1641305441847742464

that's better

`crane cp gcr.io/k8s-staging-kind/local-path-provisioner:v0.0.23-kind.0 kindest/local-path-provisioner:v0.0.23-kind.0`

**Comment by BenTheElder** [comment]
this image will be included in v0.18.0 ... tentatively tomorrow ...

**Pull request merged**
