### PR TITLE
Fix COC link.

### PR DESCRIPTION
**Pull request by tao12345666333**

### CODE REVIEW

**Comment by tao12345666333** [comment]
ref: https://github.com/kubernetes-sigs/kind/pull/31
 kubernetes/community#2700

**Comment by tao12345666333** [comment]
@BenTheElder  Thanks. :+1: 

As described in the [GitHub help docs](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/) , maybe it's the "best practices".

**Comment by nikhita** [comment]
@tao12345666333 thanks for the PR! However, as per GitHub's reply (https://github.com/kubernetes/community/pull/2700#issuecomment-424504512), we won't be renaming our code of conduct file. https://github.com/kubernetes-sigs/kind/pull/33 just got merged.

Closing.
/close

**Comment by tao12345666333** [comment]
@nikhita Thanks.

**Pull request closed without merging**
