### PR TITLE
fix cli.Logger.writeBuffer

### PR DESCRIPTION
**Pull request by BenTheElder**
fixes logging empty strings

### CODE REVIEW

**Comment by aojea** [comment]
is the second failure in a PR I see today, is this a trend or was a casualty?
/test pull-kind-conformance-parallel-1-13

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_kind/1059/pull-kind-conformance-parallel-1-13/1191980418304315398/

that's a common prow flake

the other one is a kubectl e2e flake.

however https://github.com/kubernetes-sigs/kind/issues/999 is still kicking

**Pull request merged**
