### PR TITLE
Add argument to control passing proxy envs from host

### PR DESCRIPTION
**Pull request by AryanSharma9917**
Added argument to control passing proxy envs from host #3293

Here I added a new feature to kind that allows users to control the passing of proxy environment variables to containers. By introducing a --no-env-pass argument, users can disable the inclusion of proxy environment variables when creating kind clusters. This gives users more control over their development environment, especially when proxy settings may interfere with cluster functionality.

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
i will comment on the issue

**Comment by stmcginnis** [comment]
/title Add argument to control passing proxy envs from host

Looks like you accidentally picked up a few extra commits on this.

**Comment by stmcginnis** [comment]
/retitle Add argument to control passing proxy envs from host

Looks like you accidentally picked up a few extra commits on this.

**Comment by aojea** [comment]
/hold 

env variables can be overriden , no need for flags, https://github.com/kubernetes-sigs/kind/issues/3293#issuecomment-1620345456

**Comment by BenTheElder** [comment]
In the future we should wait for discussion of features before implementing them, per the contributor guide.

I don't think we're in agreement to accept this feature.

**Pull request closed without merging**
