### PR TITLE
Clean up extra spaces

### PR DESCRIPTION
**Pull request by jayonlau**
Clean up extra spaces, although these errors are not important, they affect the code specification.

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/ok-to-test

**Review by tao12345666333 — COMMENTED** [review]
/lgtm

**Comment by aojea** [comment]
/approve
Thanks

**Comment by tao12345666333** [comment]
Github actions need re-run.

**Comment by BenTheElder** [comment]
not worth it, they're not testing this change anyhow.

**Comment by tao12345666333** [comment]
When it is not possible to merge manually(no permission), the default can only rely on passing all checks to merge. 😂

**Comment by BenTheElder** [comment]
yeah but it requires just as much permission to run them again 🙃

**Comment by BenTheElder** [comment]
this is a reason we should maybe not rely so heavily on github actions.

**Comment by tao12345666333** [comment]
Yes, if we close and then reopen, we can make it run again, but this is not a good experience 😂

**Pull request merged**
