### PR TITLE
Fetch the sha256 directly

### PR DESCRIPTION
**Pull request by MaXinjian**
Signed-off-by: Ma Xinjian <maxj.fnst@fujitsu.com>

### CODE REVIEW

**Comment by aojea** [comment]
/ok-to-test
/lgtm
Thanks

**Review by tao12345666333 — COMMENTED** [review]
/lgtm

**Comment by BenTheElder** [comment]
/approve
release is in flight and this can afford to be in the next release
/hold

**Comment by BenTheElder** [comment]
sorry we had a mishap with marking v0.11 and I pushed to main. that won't happen again, the branch is protected from this.

I just rebased this PR to fix that. Only a trivial rebase, no conflicts / changes.

/lgtm
/approve

thank you!

**Pull request merged**
