### PR TITLE
carry PR 807

### PR DESCRIPTION
**Pull request by BenTheElder**
we've had multiple attempts at this, so while I personally don't think this is an improvement, carrying it to at least be the same on both and to put one command to a line when we use code blocks

/cc @aojea 

fixes #807

### CODE REVIEW

**Comment by BenTheElder** [comment]
Hmm netlify isn't showing

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/1043#issuecomment-548809384

**Comment by aojea** [comment]
/lgtm

> we've had multiple attempts at this,

it's a cosmetic change that people seems to like ;)

**Comment by BenTheElder** [comment]
Normally with N=2 I'd not be so easily swayed but Jim is on the docs team so :-)

**Comment by BenTheElder** [comment]
Netlify is still unable to deploy due to upstream issues, but I rendered this locally.

**Pull request merged**
