### PR TITLE
automate collecting contributors

### PR DESCRIPTION
**Pull request by BenTheElder**
way better than doing it by hand

### CODE REVIEW

**Comment by BenTheElder** [comment]
/hold
forgot the uniq on the last list

**Comment by BenTheElder** [comment]
/hold cancel
added `uniq` on the last list and tested

**Comment by BenTheElder** [comment]
```
$ GITHUB_OAUTH_TOKEN="<snip>" LAST_VERSION_TAG=v0.8.1 hack/release/get-contributors.sh
Contributors since v0.8.1:
- @afbjorklund
- @aledbf
- @amwat
- @aojea
- @BenTheElder
- @damdo
- @dims
- @ericsyh
- @faiq
- @giuseppe
- @HadesArchitect
- @Hellcatlk
- @inercia
- @izzyleung
- @jayunit100
- @k8s-ci-robot
- @liggitt
- @peteroneilljr
- @prasadkatti
- @rcarrillocruz
- @rikatz
- @SataQiu
- @sozercan
- @tao12345666333
- @vdice
- @yashbhutwala
- @zhijianli88
```

**Comment by aojea** [comment]
/lgtm
```
@k8s-ci-robot
```
:robot:

**Comment by BenTheElder** [comment]
/retest
Pod pending timeout

**Pull request merged**
