### PR TITLE
add v1alpha2 config version

### PR DESCRIPTION
**Pull request by fabriziopandini**
This PR adds v1alpha2 config version.

v1alpha2 currently is copy/paste from v1alpha1, but in following PRs it will be modified for supporting multi node as defined https://github.com/kubernetes-sigs/kind/issues/130.
 
Fuzzer tests were added to make sure conversion works.
Ending test for the new version were added as well

**Note for reviewers** 
To make everyhing work it was necessary to update some dependencies, and this accounts the size of the PR 😭(all deps are in a separated commit)  :
- `k8s.io/apimachinery` and `k8s.io/code-generator` now are both from master branch (before `k8s.io/code-generator` was pinned to `release-v1.11`)
- vendored `k8s.io/apimachinery`, `k8s.io/code-generator` and `k8s.io/gengo` where updated to get a consistent set of dependencies after the switch to klog

### CODE REVIEW

**Comment by fabriziopandini** [comment]
Updated 2nd commits only (gopkg +external dependencies) to pass verify

**Comment by fabriziopandini** [comment]
@BenTheElder failures in conformance test IMO are unrelated to this PR.
How can I get around this?

**Comment by alejandrox1** [comment]
Think the errors may be related to https://github.com/kubernetes/kubernetes/issues/71614
For now, just /retest

**Comment by BenTheElder** [comment]
Kubernetes master is broken currently (CNI version mismatch) https://github.com/kubernetes/kubernetes/pull/71629 to fix.

Will loop back around to `kind` PRs after sorting upstream.

**Comment by munnerz** [comment]
This looks good to me, and is now passing tests too 😄

/lgtm

**Comment by BenTheElder** [comment]
This got flakier in recent releases too:
```
I1206 03:08:40.329] Summarizing 1 Failure:
I1206 03:08:40.329] 
I1206 03:08:40.329] [Fail] [k8s.io] [sig-node] Events [It] should be sent by kubelets and the scheduler about pods scheduling and running  [Conformance] 
```
:/
/retest

**Pull request merged**
