### PR TITLE
docs: added contributor over time

### PR DESCRIPTION
**Pull request by juzhiyuan**
Hi, this PR aims to add Contributor Over Time for Kind since 2018-07-24.

### CODE REVIEW

**Comment by BenTheElder** [comment]
What is the Purpose of this? Won't it go out of date? Why wouldn't people just check GitHub?

**Comment by juzhiyuan** [comment]
ok, this graph shows that the trend for kind repo :) As for one link with dynamically generated data, this feature is still in development, once it's done, I would add it back. Does that make sense?

**Comment by BenTheElder** [comment]
While this is cool to know we already have a lot of information for people to consume here. I don't think this is the right page for it and I'd rather not include external content we don't control, the Kubernetes documentation guidelines are against this.

**Comment by juzhiyuan** [comment]
Got it, thanks!

**Pull request closed without merging**
