### PR TITLE
Reduce base image size.

### PR DESCRIPTION
**Pull request by tao12345666333**
Remove /tmp/cni.tgz file. 

```
# du -sh /tmp/cni.tgz
15M     /tmp/cni.tgz

```

### CODE REVIEW

**Comment by munnerz** [comment]
You'll need to regenerate the go-bindata files to resolve the test failure. There should be a script for that in hack/

This seems like a sensible change, I'll defer to @bentheelder for lgtm however as I'm not in a position to run a full build & test right now!

**Comment by tao12345666333** [comment]
@munnerz  Thanks.  Let me see.

**Comment by BenTheElder** [comment]
Thanks! Looks like verify is failing for two reasons:

1) this is go 1.11 gofmt vs go < 1.11 gofmt, please use 1.11 (sorry! Will add this to development guides ref #4)

```
func (nh *nodeHandle) CopyTo(source, dest string) error {
 	cmd := exec.Command("docker", "cp")
 	cmd.Args = append(cmd.Args,
-		source, // from the source file
+		source,               // from the source file
 		nh.nameOrID+":"+dest, // to the node, at dest
 	)
```

2) I think you've got an `entrypoint` binary on disk somehow that is getting included in the generated sources:
```
-var _imagesBaseEntrypointEntrypoint = 
...
```
This shouldn't happen. I'd be curious if you have any idea how it did but in the meantime can you remove it then run hack/update-generated?

**Comment by BenTheElder** [comment]
> And I have build the entrypoint binary for test build base image locally.

Did you use docker build manually? `kind build base` should automatically stage the build into a tempdir which should prevent this (and other things).

**Comment by tao12345666333** [comment]
Yes, I run docker build manually. 😂😂😂
Thanks for your suggestion, I will use kind instead it.

**Comment by BenTheElder** [comment]
Awesome, thanks. Wanted to make sure there wasn't a bug in that :-)

If you can fix the generated file this LGTM 👍

**Comment by tao12345666333** [comment]
@BenTheElder Thanks, addressed.

**Comment by BenTheElder** [comment]
hmmm did something change with approval?
/approve

**Pull request merged**
