### PR TITLE
Updated copy button

### LINKED ISSUE #3269: Copy button not working
**What you expected to happen**:
copy the code 

**How to reproduce it (as _minimally_ and precisely as possible)**:
On [this](https://kind.sigs.k8s.io/docs/user/quick-start/) page
Try to copy code with the use of copy symbol

### PR DESCRIPTION
**Pull request by AryanSharma9917**
Fixed #3269
Added tick confirmation to the copy button on [this](https://kind.sigs.k8s.io/docs/user/quick-start/) page.

### CODE REVIEW

**Comment by aojea** [comment]
my skills here are close to zero 😄 
/assign @BenTheElder

**Comment by BenTheElder** [comment]
I took a quick peek and what I see is it throws javascript errors and no longer shows the icon.
/hold
/lgtm cancel

**Comment by AryanSharma9917** [comment]
> I took a quick peek and what I see is it throws javascript errors and no longer shows the icon. /hold /lgtm cancel

Sorry, about that I'll look into it!

**Comment by AryanSharma9917** [comment]
> I took a quick peek and what I see is it throws javascript errors and no longer shows the icon. /hold /lgtm cancel

And one more help is there any document or something for the localhosting ?
I was facing some issues while testing it, it would be great if you help me out with that!

**Comment by BenTheElder** [comment]
Our contributing guide includes the docs

**Comment by stmcginnis** [comment]
Can you squash your commits?

**Comment by AryanSharma9917** [comment]
> Can you squash your commits?

Is it okay now? And also please re-review it now the copy button is working as shown in deploy/netify preview.

**Comment by AryanSharma9917** [comment]
> I took a quick peek and what I see is it throws javascript errors and no longer shows the icon. /hold /lgtm cancel

Heyy @BenTheElder could you please review my PR

**Comment by AryanSharma9917** [comment]
Hey @BenTheElder @stmcginnis could you please review this PR?

**Comment by stmcginnis** [comment]
Sorry for the delay getting back. Looks like you still have a few "Done some changes" commits in the chain. Can you squash those into one commit? (`git rebase -i HEAD~4`?).

**Comment by Sajiyah-Salat** [comment]
Hello @AryanSharma9917 I was quite busy these days. you have asked me twice to assign issue. here in kubernetes-sigs you can assign yourself issue by just commenting `/assign` . Looks like your pr will be merged shortly.

**Review by BenTheElder — COMMENTED** [review]
can we please keep the existing icon? I only see an emoji now.

**Comment by AryanSharma9917** [comment]
> Emoji generally shouldn't be used for critical information, e.g. the local client may not have a font to render them or may render them poorly. Using an image / icon avoids this (github for example ensures a fallback image based render for any image).

Hey @BenTheElder, I have made the changes could you please give it a look.

**Comment by AryanSharma9917** [comment]
@aojea @neolit123, could you please take a look at my PR?

**Comment by AryanSharma9917** [comment]
Hey @BenTheElder, could you please review my PR

**Comment by AryanSharma9917** [comment]
> Hey @BenTheElder, could you please review my PR

@aojea

**Pull request closed without merging**
