### PR TITLE
use 'command -v' instead of 'which' in bash scripts

### PR DESCRIPTION
**Pull request by zegl**
command -v is a shell builtin, this change is recommended by shellcheck.

This updates #528

### CODE REVIEW

**Comment by BenTheElder** [comment]
Thanks for the PR, but actually these are not equivalent, https://github.com/koalaman/shellcheck/issues/1162

We are in fact looking for the gnu-sed binary specifically, `command -v` matches against aliases etc which we do _not_ want. In the Kubernetes main repo we've disabled SC2230.

`which` is available on pretty much any modern posix-y system.

**Comment by zegl** [comment]
It seems like you're right, I'll close this PR. :)

**Pull request closed without merging**
