### PR TITLE
pre-pull images that are not part of the build

### PR DESCRIPTION
**Pull request by fabriziopandini**
fixes: https://github.com/kubernetes-sigs/kind/issues/30

Since docker in docker is not available at build time, I'm using docker of the host machine for pre-pulling images. This has the advantage that pre-pulled images are reused in subsequent builds...

@BenTheElder 
I saw only now this was already active 😭 feel free to close it

### CODE REVIEW

**Comment by BenTheElder** [comment]
Thanks for the PR!

I like the pull to host approach, but I think maybe we need a slightly different approach regarding detecting which images. The presubmit is failing because we're trying to pull images that we actually built that don't exist upstream.

**Comment by fabriziopandini** [comment]
@BenTheElder 
If we rely on kubeadm config images what I can do is to detect that kebernetes version is a build version and then prefix with ci/ the version number passed to kubeadm (this should shift from `k8s.gcr.io` to `gcr.io/kubernetes-ci-images`). And as additional measure I can make pre-pull errors not blocking.
Wdyt?

**Comment by BenTheElder** [comment]
It shouldn't be pulling this image at all as it has a local copy. It shouldn't need to pull any images from ci/ as we build all of those (except apt "build", which also shouldn't have ci/ images...)

**Comment by BenTheElder** [comment]
Thanks for working on this, I implemented something pretty similar in https://github.com/kubernetes-sigs/kind/pull/89, though it detects which images don't need pulling a bit differently.

**Comment by fabriziopandini** [comment]
@BenTheElder sorry for not following up.
I plan to get back on helping on kind after release cut

**Pull request closed without merging**
