### PR TITLE
synchronize exec combined output buffer when necessary

### PR DESCRIPTION
**Pull request by BenTheElder**
When we execute things in kind we capture the output in case of an error and provide this when debugging. This is very handy, but had a nasty bug, xref: #971.

When `cmd.Stdout == cmd.Stderr`, go will set up a single fd passed to the underyling process,  and single `io.Copy` goroutine will be used for that fd. This makes it safe to share a buffer between `cmd.Stdout` and `cmd.Stderr` IFF `cmd.Stdout == cmd.Stderr`.

When this is not the case, we need to synchronize writes to the combined output buffer.

See: 
- https://go-review.googlesource.com/c/go/+/42052/ (`os/exec: document that non-comparable writers may race`)
- https://github.com/golang/go/blob/72275c0dea7887597e3e445676674ba6af702f06/src/os/exec/exec.go#L216-L223
- https://github.com/golang/go/blob/72275c0dea7887597e3e445676674ba6af702f06/src/os/exec/exec.go#L282-L287

fixes: #971

### CODE REVIEW

**Comment by BenTheElder** [comment]
IPv6 e2e flakes
/test pull-kind-conformance-parallel-ipv6

**Comment by aojea** [comment]
nice catch and thanks to @liggitt for keep finding occurrences
/lgtm

the ipv6 flakes show errors with some application holding the lock, I'm trying to investigate more

**Comment by BenTheElder** [comment]
> the ipv6 flakes show errors with some application holding the lock, I'm trying to investigate more

[iptables, on the node, not the lock we introduced here]

**Pull request merged**
