### PR TITLE
add a kind get images command to query docker hub for available images

### PR DESCRIPTION
**Pull request by hubt**

### CODE REVIEW

**Comment by BenTheElder** [comment]
Hi, please see the previous PR for this.

**Comment by BenTheElder** [comment]
And in general, please file an issue to discuss feature additions & design before filing PRs, I beleive we have a note about this in the docs, thanks!

**Comment by BenTheElder** [comment]
for this feature specifically: not all image tags are going to work for a given kind version, there is more on this in the release notes https://github.com/kubernetes-sigs/kind/releases

**Comment by BenTheElder** [comment]
(meant to comment, clicked close and comment)

**Comment by hubt** [comment]
Per slack discussion:
* sorry I didn't open an issue first, I meant to.
* docker hub may not be secure enough for this, this could expose kind users to some vulnerabilities if docker hub is compromised.
* this doesn't provide a solution to resolve incompatibilities between kind versions and node images which won't work with all kind versions.
So I'll close this and see if I can work on this in a different way.

**Pull request closed without merging**
